### ISSUE TITLE
cant add bridge again to home assistant after deleting it

### ISSUE THREAD

**Issue by tammeryousef1006** [Luligu/matterbridge#10]
this is the msg i got from log upon starting 
(The commissioning server for Matterbridge is already commissioned. Waiting for controllers to connect)

is there anyway to force commission again ?

many thanks bro

**Comment by tammeryousef1006** [comment]
i stopped matter bridge and run it again in childbridge mode and that solved my issue , but in the future is it possible to delete matter fabric and add it again ? because at log it doesnt show that its removed , it shows still commissioned

**Comment by Luligu** [comment]
Hi,
thank you for your message and interest.
Normally when you remove a device (e.g. the Matterbridge aggregator in your case) from the controller, Matterbridge removes the commissioning information so you can pair it again. 
When you remove a device when Matterbridge is not running, you can find yourself in the situation you described.
Since this can happen:
- I added a new parameter to the command line: -reset [plugin]: this removes the plugin commissioning information (childbridge mode).
- I added a new parameter to the command line: -factoryreset: this removes the commissioning information for Matterbridge.
Both will be included in the next release after a few tests.

**Comment by tammeryousef1006** [comment]
Many thanks for your reply

Awaiting next release.  Just a note i added plug and motion sensor and it's
both working fine at home assistant.  Whenever i pair with ewelink hub i
see the plug only , is this issue from ewelink hub or that matter motion
sensors not supported yet ?

Best regards

**Comment by Luligu** [comment]
Sorry but I cannot answer, I have 0 knowledge of ewelink support of Matter.

I was wondering if you could be so kind to make a kind of list of what of Matter is not supported in ewelink (maybe installing  the 7 example plugins).

**Comment by tammeryousef1006** [comment]
sure i will try my best to test the 7 examples and i will give you  a
feedback about it

**Comment by Luligu** [comment]
Thanks, I appreciate it.

**Comment by tammeryousef1006** [comment]
i already tried to reset many times , but it keep showing ([Matterbridge]
The commissioning server for Matterbridge is already commissioned. Waiting
for controllers to connect)
and at matterbridge webpage shows all as paired . i tried to run in
matterbridge child mode and pair with ewelink , (door,motion,weather,room)
got a pop up from ewelink saying not supported yet , for zigbee2mqtt i
success to link a zigbee plug switch off on , other examples failed to
catch at commission , just to give a hint regarding ewelink matter hub is
still in beta stage.


Best regards

**Comment by tammeryousef1006** [comment]
i attached some photos if it may help regarding the reset failing to unpair

**Comment by tammeryousef1006** [comment]
Hello there

i did reinstall all from scratch to get over the reset failing , i did try
all plugins with ewelink and only the plug from zigbee2mqtt appear and 1
other switch ( i guess only supporting switches in this case ) , after that
i tried with tuya app itself without a hub , it detect the aggregator only
without any other devices , i tried with google home it gave same results ,
the only case that i saw all devices were at home assistant only .

Best Regards Bro

**Comment by Luligu** [comment]
Hi, 
I published only now.
Update Matterbridge and plugins.

**Comment by tammeryousef1006** [comment]
Many thanks bro for following up on this

i already tested again the matterbridge-zigbee2mqtt after adding plug and
door contact sensor but this time with smarthings hub , its fully working
like a charm <3 , kindly see the attached pic  , is it normal that the
zigbee plug always detected as switch ?

**Comment by tammeryousef1006** [comment]
Hello . I tested all plug-ins with smartthings and they all appear to be
working . Kindly see attached.


Best regards
