### ISSUE TITLE
Problem updating shelly plugin - file cannot be renamed

### ISSUE THREAD

**Issue by dmshimself** [Luligu/matterbridge#100]
I have installed a fresh docker copy of matterbridge and installed/configured the shelly plugin. I see there is an upgrade available, see screenshot below. But when I apply this I get an error when a file is renamed, also see below.

![1](https://github.com/user-attachments/assets/a3751d62-7c00-4ff5-9506-ab79a3fa6ea2)
![2](https://github.com/user-attachments/assets/ed093757-4e7e-463d-8e35-f5cd0208683c)

As a test, I tried to rename the file manually and I get the following:

docker exec matterbridge mv '/usr/local/lib/node_modules/matterbridge-shelly/CHANGELOG.md' '/usr/local/lib/node_modules/.matterbridge-shelly-qZ4KFENC/CHANGELOG.md'

mv: cannot move '/usr/local/lib/node_modules/matterbridge-shelly/CHANGELOG.md' to a subdirectory of itself, '/usr/local/lib/node_modules/.matterbridge-shelly-qZ4KFENC/CHANGELOG.md'

**Comment by Apollon77** [comment]
Thats an npm bug somehow ... I've seen that before. delete this directory /usr/local/lib/node_modules/.matterbridge-shelly-qZ4KFENC/ manually and try again

**Comment by dmshimself** [comment]
Many thanks for the speedy suggestion.  No joy though I'm afraid.  I tried the same for the zigbee plugin.  I did with and without restarting matterbridge with the same result.

**Comment by Luligu** [comment]
Hi,
I'm currently on holiday so no access to my network.

But I would try also this:
```
docker exec -it matterbridge /bin/bash
```
inside the shell
```
npm -g install matterbridge-shelly matterbridge-zigbee2mqtt
```

**Comment by dmshimself** [comment]
Perfect - works very well.  Many thanks

**Comment by Luligu** [comment]
Hi,
thanks for the feedback.
Lately this npm or docker issue has been reported more than once.
I don't understand why...
@Apollon77 do you know something more? The fronted just spawn the same command... nothing changed there since months.

**Comment by Apollon77** [comment]
We also have that a lot. Seems to happen in some cases where npm just leaves some temporary dirs existing after an action and then has issues when it sees them again. We added a cleanup command which deletes all this.
