### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by MarcusNotheis** [Luligu/matterbridge#101]
I've tried to setup matterbridge by following the instructions from the Readme (`sudo npm install -g matterbridge
 && matterbridge -bridge`), but when running `matterbridge -bridge`, the startup is crashing:

```
file:///Users/<REDACTED>/.nvm/versions/node/v20.16.0/lib/node_modules/matterbridge/dist/matterbridge.js:2481
            this.log.debug(`WebSocketServer logger global callback: ${this.log.getGlobalCallback() ? 'active' : 'inactive'}`);
                                                                               ^

TypeError: this.log.getGlobalCallback is not a function
    at file:///Users/<REDACTED>/.nvm/versions/node/v20.16.0/lib/node_modules/matterbridge/dist/matterbridge.js:2481:80
```
There seems to be something around the `this.log.setGlobalCallback` and `this.log.getGlobalCallback` function as both are undefined in my installation. If I comment out the line below, I can at least start the matterbridege:

https://github.com/Luligu/matterbridge/blob/e3d21e95f9af275662646ab560c479c0d00872bd/src/matterbridge.ts#L2601

Environment:
```
System: MacOS Sonoma 14.6.1 (23G93)
Node-Version: v20.16.0
Matterbridge: 1.4.1
```

**Comment by MarcusNotheis** [comment]
Could be an issue with the dependency `ansi-logger`: in 2.0.7, the `setGlobalCallback` and `getGlobalCallback` have been made static, and with `^2.0.6` from the matterbridge package.json I now get the new version

**Comment by Luligu** [comment]
Hi,
you are absolutely right.
I wanted to publish a new release of matterbridge immediately after but I could not finish and then I forgot the side issue of new installation.
Deployment tests didn't spot the issue...
Thanks.
Fixed.
