### ISSUE TITLE
Error: Only supported EndpointInterface implementation is Endpoint

### ISSUE THREAD

**Issue by simonepittis** [Luligu/matterbridge#107]
Hi,

I moved to Matterbridge from Docker to Debian 11 dedicated machine.

NodeJS v18.20.4
NPM v10.8.2
Matterbridge v1.4.2
matterbridge-zigbee2mqtt v2.1.11

Errors:
info - [06:29:14.035] [Matterbridge]: The plugin matterbridge-zigbee2mqtt is up to date. Current version: 2.1.11, Latest version: 2.1.11
info - [06:29:14.827] [Matterbridge zigbee2mqtt plugin]: Initializing platform: matterbridge-zigbee2mqtt v
info - [06:29:14.828] [Matterbridge zigbee2mqtt plugin]: Loaded zigbee2mqtt parameters from /xxxxxx/.matterbridge/matterbridge-zigbee2mqtt.config.json:
info - [06:29:14.832] [Matterbridge zigbee2mqtt plugin]: Connecting to MQTT broker: mqtt://xxx.yyy.zzz:1883
info - [06:29:15.090] [Matterbridge zigbee2mqtt plugin]: MQTT broker at xxx.yyy.zzz:1883 connected
notice - [06:29:15.111] [PluginManager]: Loaded plugin matterbridge-zigbee2mqtt type DynamicPlatform (entrypoint /usr/lib/node_modules/matterbridge-zigbee2mqtt/dist/index.js)
info - [06:29:15.116] [PluginManager]: Starting plugin matterbridge-zigbee2mqtt type DynamicPlatform
info - [06:29:15.119] [Matterbridge zigbee2mqtt plugin]: Starting zigbee2mqtt dynamic platform v2.1.11: Matterbridge is starting
info - [06:29:15.134] [Matterbridge zigbee2mqtt plugin]: MQTT broker at xxx.yyy.zzz:1883 subscribed to: zigbee2mqtt/#
info - [06:29:15.219] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 30 devices
info - [06:29:15.237] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT sent 0 groups
info - [06:29:15.306] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT version 1.39.1 zh version 0.55.3 zhc version 19.72.0
info - [06:29:15.313] [Matterbridge zigbee2mqtt plugin]: zigbee2MQTT is online
info - [06:29:16.626] [Matterbridge zigbee2mqtt plugin]: Registering 30 devices
error - [06:29:16.957] [Matterbridge zigbee2mqtt plugin]: Error registering device Coordinator ID: 0x00124b002a2ebdd1: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.057] [Matterbridge zigbee2mqtt plugin]: Error registering device Bathroom Thermostat ID: 0x84ba20fffe29b170: Error: Only supported EndpointInterface implementation is Endpoint
info - [06:29:17.058] [Kitchen Light Switch]: Device Kitchen Light Switch has actions mapped to these switches on sub endpoints:
info - [06:29:17.059] [Kitchen Light Switch]: controller events <=> zigbee2mqtt actions
info - [06:29:17.125] [Kitchen Light Switch]: -- Button 1: Single Press <=> single_left
info - [06:29:17.126] [Kitchen Light Switch]: -- Button 1: Double Press <=> single_right
info - [06:29:17.126] [Kitchen Light Switch]: -- Button 1: Long Press <=> single_both
info - [06:29:17.203] [Kitchen Light Switch]: -- Button 2: Single Press <=> double_left
info - [06:29:17.203] [Kitchen Light Switch]: -- Button 2: Double Press <=> double_right
info - [06:29:17.204] [Kitchen Light Switch]: -- Button 2: Long Press <=> double_both
info - [06:29:17.278] [Kitchen Light Switch]: -- Button 3: Single Press <=> triple_left
info - [06:29:17.279] [Kitchen Light Switch]: -- Button 3: Double Press <=> triple_right
info - [06:29:17.280] [Kitchen Light Switch]: -- Button 3: Long Press <=> triple_both
info - [06:29:17.350] [Kitchen Light Switch]: -- Button 4: Single Press <=> hold_left
info - [06:29:17.351] [Kitchen Light Switch]: -- Button 4: Double Press <=> hold_right
info - [06:29:17.351] [Kitchen Light Switch]: -- Button 4: Long Press <=> hold_both
error - [06:29:17.418] [Matterbridge zigbee2mqtt plugin]: Error registering device Kitchen Light Switch ID: 0x54ef441000940cd9: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.500] [Matterbridge zigbee2mqtt plugin]: Error registering device Bedroom Heater ID: 0x54ef44100013898d: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.583] [Matterbridge zigbee2mqtt plugin]: Error registering device Heater Greenhouse ID: 0x54ef44100013958f: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.656] [Matterbridge zigbee2mqtt plugin]: Error registering device Bathroom Air Extractor Switch ID: 0x54ef4410001d142f: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.730] [Matterbridge zigbee2mqtt plugin]: Error registering device Giulia Bedroom Heater ID: 0x54ef44100013a5aa: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.808] [Matterbridge zigbee2mqtt plugin]: Error registering device Terrace Door Sensor ID: 0x00158d00090d59b9: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.871] [Matterbridge zigbee2mqtt plugin]: Error registering device Living Room Temperature Sensor ID: 0x00158d0009452521: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:17.939] [Matterbridge zigbee2mqtt plugin]: Error registering device Greenhouse Temperature Sensor ID: 0x00158d0008cb1d67: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.023] [Matterbridge zigbee2mqtt plugin]: Error registering device Ventilation Greenhouse ID: 0x54ef441000139006: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.093] [Matterbridge zigbee2mqtt plugin]: Error registering device Livingroom Motion Sensor ID: 0x00158d0006d3ebe3: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.159] [Matterbridge zigbee2mqtt plugin]: Error registering device Kitchen Temperature Sensor ID: 0x00158d0007d40533: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.232] [Matterbridge zigbee2mqtt plugin]: Error registering device Kitchen Main Light ID: 0x54ef44100025801b: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.313] [Matterbridge zigbee2mqtt plugin]: Error registering device Kitchen Moist Senior ID: 0x00158d00094d56bd: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.373] [Matterbridge zigbee2mqtt plugin]: Error registering device Kitchen Motion Sensor ID: 0x00158d0006e4ab5f: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.432] [Matterbridge zigbee2mqtt plugin]: Error registering device Giulia Temperature Sensor ID: 0x00158d0006e48b04: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.504] [Matterbridge zigbee2mqtt plugin]: Error registering device Giulia Motion Sensor ID: 0x00158d0006e472b6: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.565] [Matterbridge zigbee2mqtt plugin]: Error registering device Entrance Temperature Sensor ID: 0x00158d0006d6bedc: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.627] [Matterbridge zigbee2mqtt plugin]: Error registering device Entrance Motion Sensor ID: 0x00158d0006f9937b: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.694] [Matterbridge zigbee2mqtt plugin]: Error registering device Main Door Contact Sensor ID: 0x00158d0004459064: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.751] [Matterbridge zigbee2mqtt plugin]: Error registering device Steps Motion Sensor ID: 0x00158d0006ebc3fe: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.806] [Matterbridge zigbee2mqtt plugin]: Error registering device Steps Temperature Sensor ID: 0x00158d0006f12e27: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.861] [Matterbridge zigbee2mqtt plugin]: Error registering device Walkin Closet Motion Sensor ID: 0x00158d0006c032b1: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.929] [Matterbridge zigbee2mqtt plugin]: Error registering device Bedroom Motion Sensor ID: 0x00158d0006d3de94: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:18.988] [Matterbridge zigbee2mqtt plugin]: Error registering device Bathroom Motion Sensor ID: 0x00158d0006f3d1ed: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:19.049] [Matterbridge zigbee2mqtt plugin]: Error registering device Bathroom Moist Sensor ID: 0x00158d00094d7933: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:19.107] [Matterbridge zigbee2mqtt plugin]: Error registering device Bathroom Temperature Sensor ID: 0x00158d0006e3b5bc: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:19.170] [Matterbridge zigbee2mqtt plugin]: Error registering device Bedroom Heater Floor ID: 0x54ef4410007b07e5: Error: Only supported EndpointInterface implementation is Endpoint
error - [06:29:19.232] [Matterbridge zigbee2mqtt plugin]: Error registering device Lighthouse Light Switch ID: 0x54ef44100070e9f7: Error: Only supported EndpointInterface implementation is Endpoint
info - [06:29:19.232] [Matterbridge zigbee2mqtt plugin]: Registering 0 groups
info - [06:29:19.232] [Matterbridge zigbee2mqtt plugin]: Started zigbee2mqtt dynamic platform v2.1.11: Matterbridge is starting
notice - [06:29:19.233] [PluginManager]: Started plugin matterbridge-zigbee2mqtt type DynamicPlatform
notice - [06:29:19.310] [Matterbridge]: Matter server started

after all the Matterbridge crash an restarting

**Comment by Luligu** [comment]
Hi,
are you using any home assistant plugins?

**Comment by simonepittis** [comment]
no

Zigbee2MQTT stand alone
Matterbridge stand alone + z2m plugin

On docker works, on Debian no

**Comment by Luligu** [comment]
Hi,
thanks for the fast reply.

This issue is only seen with the homeassistant plugin cause they import twice matter-node instead of importing from matterbridge.

Do you use daemon for matterbridge ?

Any LXC script ?

Any other info that can be useful?

Can you send me a full console log from the start please cause we have never been able to replicate.

**Comment by simonepittis** [comment]
yes I use daemon. config like in the Readme +ssl (ExecStart=matterbridge -bridge -ssl -service)

No LXC

it's Debian 11 on aarch64 (Rock Pi 4C+), standard config and only this.

I will send you the full log this evening when I back at home

**Comment by tammeryousef1006** [comment]
> Hi, thanks for the fast reply.
> 
> This issue is only seen with the homeassistant plugin cause they import twice matter-node instead of importing from matterbridge.
> 
> Do you use daemon for matterbridge ?
> 
> Any LXC script ?
> 
> Any other info that can be useful, cause we never ever reproduced that issue? Like exactly the sequence you followed to install?
> 
> Can you send me a full console log from the start please cause we have never been able to replicate. Add -logger debug parameter please.
> 
> @tammeryousef1006 did you ever seen that without the homeassistant plugin?

i never faced issue like that , but I saw similar with the script of proxmox were devices getting detected and not saved , 
it might be not following setup instruction correctly , I will try to simulate this today at home and see the results and get back to you asap

**Comment by simonepittis** [comment]
thanks

> dear @simonepittis have you done this step ?
> 
> https://github.com/Luligu/matterbridge?tab=readme-ov-file#advanced-configuration

yes. without zigbee2mqtt plugin works without problems.

**Comment by simonepittis** [comment]
the matterbridge works like daemon. the issue start when i use the zigbee2mqtt plugin

**Comment by tammeryousef1006** [comment]
im simulating this right now , will find out soon and get back to you many thanks

**Comment by tammeryousef1006** [comment]
updated z2m plugin already , thanks for help

**Comment by simonepittis** [comment]
you too :-)
