### ISSUE TITLE
Can not add device from Google Home

### ISSUE THREAD

**Issue by minhtaidev** [Luligu/matterbridge#110]
Dear Luligu, I can not add Matter device from Google Home app (Android). Google system reports that the device has not been authenticated.
Please support. Thank you.

**Comment by Luligu** [comment]
Hi,
thank you for your interest.

https://github.com/Luligu/matterbridge?tab=readme-ov-file#google-home

There you should find some info to solve your issue.

**Comment by minhtaidev** [comment]
Dear Luligu, thanks for your reply.
I follow suggestion in closed issue and meet connection issue as picture and log_matter.txt below
![d246867bcc2a6b74323b](https://github.com/user-attachments/assets/f004e289-1bae-4ac2-a43d-57c1940cd1d9)
- Already open port 5540 (tcp/udp) on linux device
- Mobile (google home app) and linux device same wifi
[log_matter.txt](https://github.com/user-attachments/files/16754987/log_matter.txt)
Please help for check.
Thank you, Luligu

**Comment by Luligu** [comment]
@tammeryousef1006 can you help please?

**Comment by tammeryousef1006** [comment]
dear @minhtaidev  , kindly answer some questions and provide me with some details please ,
- whats the android version of your mobile? aside of matterbridge do you have any other matter devices connected to google home ?
- what the router name/model you are using ?
- have you tried to pair to matterbridge without adding any plugins ? if not yet then give it a try please 
-  please provide a log for matter bridge
