### ISSUE TITLE
How to completely remove Matterbridge and plugins Linux

### ISSUE THREAD

**Issue by ionutm80** [Luligu/matterbridge#114]
Hi, as the title states what is the linux cli command to completely remove Matterbridge and Shelly plugin? Last update completely broke my instalation and I'm not going to use it anymore.
Thanks in advace for your understanding! 
![IMG_5202](https://github.com/user-attachments/assets/e95c5c32-4b9c-4b1b-b0e8-e0c3db7b54d9)

**Comment by ionutm80** [comment]
Figure it out myself!

**Comment by Luligu** [comment]
That message was the storage that get corrupted...
