### ISSUE TITLE
Thermostat dosent work in SmartThings

### ISSUE THREAD

**Issue by SebastianKristo** [Luligu/matterbridge#118]
The thermostat changes both the target temperature and state after adjustments made in Home Assistant, but changes made in SmartThings do not take effect.

**Comment by Luligu** [comment]
Hi,
can you be more specific please?
Are you talking about z2m plugin?
What version are you using, what plugins?
Thanks

**Comment by SebastianKristo** [comment]
I expose a wifi thermostat to the homeassistant matterbridge add-on.

**Comment by Apollon77** [comment]
I propose you enable debug log and control via smartthings and then we see whats up

**Comment by vvifeel** [comment]
Same issue. Here's the log I got.
[InteractionServer]: Error while handling write request from udp://~~~~~~~~~~~~~~ on session secure/5261 to MA-thermostat(0xf)/Thermostat(0x201)/systemMode(0x1c): (136) Fixed attributes cannot be written

**Comment by Apollon77** [comment]
Hm .. in matter.js the systemMode attribute is a writeable one and not fixed ... interesting ...  @Luligu do you have an own cluster definition one here?

**Comment by Luligu** [comment]
In general I'm always happy to help with Matterbridge, but those are not my plugins so this is not the correct place to open issues unless they are related to Matterbridge or matter.js commissioning.

Activete the log on file, restart and download matterbridge.log and send it please.
<img width="234" alt="image" src="https://github.com/user-attachments/assets/9ac92753-2914-451d-b9ce-0e69958ed882">
