### ISSUE TITLE
Testing RGBW lights on the Apple Homekit app,

### ISSUE THREAD

**Issue by sky987654** [Luligu/matterbridge#119]
Excuse me, I added the RGBW light to the Apple Homekit app for testing and found that when clicking on the color temperature shown in the picture below, the app did not send any values. Everything else is fine. Thank you.
![RGBW](https://github.com/user-attachments/assets/b3139b8c-9383-45ea-8990-5f6c50813c0a)
Also, by the way, do you have any plugins for lights that only adjust brightness and color temperature. thank you very much.

**Comment by Luligu** [comment]
Hi,
can you be more specific please?
What plugin are you using ?
Lights are in all plugins...

**Comment by sky987654** [comment]
The type of device I am using is:DeviceTypes.ON_OFF_LIGHT
If it's convenient, you can add it to HomeKit to take a look，thank you very much.

**Comment by Apollon77** [comment]
ON_OFF_LIGHT is just having ON-Off functionality!! SO yes it would be expected that no dimming works

**Comment by sky987654** [comment]
Perhaps so, but the Homekit interface has a dimming slider

**Comment by Luligu** [comment]
Sorry,
but what plugin are you using?
On HomeKit shows like an on/off light only no dimmer and no color temp selector.

**Comment by sky987654** [comment]
Sorry, I've been quite busy lately. I'm using this type：
ON_OFF_LIGHT: DeviceTypeDefinition({
        name: "MA-onofflight",
        code: 0x0100,
        deviceClass: DeviceClasses.Simple,
        revision: 2,
        requiredServerClusters: [
            MatterClusters.IdentifyCluster.id,
            MatterClusters.GroupsCluster.id,
            //MatterClusters.ScenesCluster.id,
            MatterClusters.OnOffCluster.id,
        ],
        optionalServerClusters: [MatterClusters.LevelControlCluster.id],
        optionalClientClusters: [MatterClusters.OccupancySensingCluster.id],
    }),

Thank you very much.

**Comment by Luligu** [comment]
Sorry but I don't understand: 
Are you using Matterbridge or what?
What plugins?

**Comment by sky987654** [comment]
I found that deleting this attachment from the HomeKit app and restarting it to add it is enough. Perhaps it was caused by the phone cache. Sorry, thank you!

**Comment by sky987654** [comment]
I recently found out that RGBW cannot be adjusted to the boundary value through color card adjustment in HomeKit. I took a video, is this normal?

https://github.com/user-attachments/assets/cd06dba0-3a55-4e9b-b1b5-cc735bd07c3c

**Comment by sky987654** [comment]
Thank you very much!

**Comment by sky987654** [comment]
Sorry for not replying due to being busy. The Homekit app currently supports RGBW, and the above situation is normal. thank you!
