### ISSUE TITLE
Error installing shelly plugin after updating matterbridge to 1.5.4

### ISSUE THREAD

**Issue by ionutm80** [Luligu/matterbridge#124]
Hi, last night I have seen the yellow label to update matterbridge to 1.5.4 and shelly plugin to 0.9.5. After updating matterbridge I deleted shelly plugin and tried to install it again but it gives errors now, see the logs below:

info - [07:25:36.926] [Matterbridge]: WebSocketServer client "::ffff:192.168.88.91" connected to Matterbridge
Plugins - Installing plugin: matterbridge-shelly
info - [07:25:52.854] [Matterbridge]: Installing plugin matterbridge-shelly...
spawn - [07:25:52.985] [Matterbridge:spawn]: npm verbose cli /usr/bin/node /usr/bin/npm
spawn - [07:25:52.986] [Matterbridge:spawn]: npm info using npm@10.8.2npm info using node@v20.17.0
spawn - [07:25:52.988] [Matterbridge:spawn]: npm verbose title npm install matterbridge-shelly
spawn - [07:25:52.989] [Matterbridge:spawn]: npm verbose argv "install" "--global" "matterbridge-shelly" "--loglevel" "verbose"npm verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-09-06T04_25_52_947Z-
spawn - [07:25:52.990] [Matterbridge:spawn]: npm verbose logfile /root/.npm/_logs/2024-09-06T04_25_52_947Z-debug-0.log
spawn - [07:25:53.433] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/matterbridge-shelly 150ms (cache revalidated)
spawn - [07:25:53.524] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/coap 83ms (cache revalidated)
spawn - [07:25:53.605] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/dns-packet 80ms (cache revalidated)
spawn - [07:25:53.667] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/multicast-dns 59ms (cache revalidated)
spawn - [07:25:54.222] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/node-ansi-logger 554ms (cache revalidated)
spawn - [07:25:54.248] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/node-fetch 22ms (cache revalidated)
spawn - [07:25:54.867] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/node-persist-manager 611ms (cache revalidated)
spawn - [07:25:54.889] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/ws 20ms (cache revalidated)
spawn - [07:25:54.920] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/bufferutil 21ms (cache revalidated)
spawn - [07:25:54.943] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/utf-8-validate 19ms (cache revalidated)
spawn - [07:25:55.180] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/bl 227ms (cache revalidated)
spawn - [07:25:55.291] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/@types%2freadable-stream 109ms (cache revalidated)
spawn - [07:25:55.370] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/capitalize 75ms (cache revalidated)
spawn - [07:25:55.432] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/coap-packet 61ms (cache revalidated)
spawn - [07:25:55.452] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/debug 18ms (cache revalidated)
spawn - [07:25:55.514] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/fastseries 60ms (cache revalidated)
spawn - [07:25:55.566] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/lru-cache 51ms (cache revalidated)
spawn - [07:25:55.636] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/readable-stream 64ms (cache revalidated)
spawn - [07:25:55.804] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/@leichtgewicht%2fip-codec 164ms (cache revalidated)
spawn - [07:25:55.878] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/thunky 73ms (cache revalidated)
spawn - [07:25:55.938] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/data-uri-to-buffer 58ms (cache revalidated)
spawn - [07:25:55.994] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/fetch-blob 55ms (cache revalidated)
spawn - [07:25:56.064] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/formdata-polyfill 67ms (cache revalidated)
spawn - [07:25:56.134] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/node-persist 69ms (cache revalidated)
spawn - [07:25:56.191] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 44ms (cache revalidated)
spawn - [07:25:56.369] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 26ms (cache revalidated)
spawn - [07:25:56.428] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/buffer 58ms (cache revalidated)
spawn - [07:25:56.450] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/inherits 18ms (cache revalidated)
spawn - [07:25:56.470] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/ms 18ms (cache revalidated)
spawn - [07:25:56.534] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/abort-controller 60ms (cache revalidated)
spawn - [07:25:56.562] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/events 25ms (cache revalidated)
spawn - [07:25:56.647] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/process 82ms (cache revalidated)
spawn - [07:25:56.706] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/string_decoder 59ms (cache revalidated)
spawn - [07:25:56.772] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/undici-types 62ms (cache revalidated)
spawn - [07:25:56.797] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/base64-js 18ms (cache revalidated)
spawn - [07:25:56.861] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/ieee754 60ms (cache revalidated)
spawn - [07:25:56.960] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/node-domexception 83ms (cache revalidated)
spawn - [07:25:57.021] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/web-streams-polyfill 58ms (cache revalidated)
spawn - [07:25:57.094] [Matterbridge:spawn]: npm http fetch GET 200 https://registry.npmjs.org/event-target-shim 61ms (cache revalidated)
spawn - [07:25:57.139] [Matterbridge:spawn]: npm verbose stack Error: ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/matterbridge-shelly' -> '/usr/lib/node_modules/.matterbridge-shelly-c8EH9AG9'npm verbose stack at async Object.rename (node:internal/fs/promises:782:10)npm verbose stack at async moveFile (/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/move-file.js:30:5)npm verbose stack at async Promise.allSettled (index 0)npm verbose stack at async [reifyPackages] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)npm verbose stack at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)npm verbose stack at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:150:5)npm verbose stack at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)npm verbose stack at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)npm error code ENOTEMPTYnpm error syscall renamenpm error path /usr/lib/node_modules/matterbridge-shellynpm error dest /usr/lib/node_modules/.matterbridge-shelly-c8EH9AG9npm error errno -39npm error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/matterbridge-shelly' -> '/usr/lib/node_modules/.matterbridge-shelly-c8EH9AG9'npm verbose cwd /root/Matterbridgenpm verbose os Linux 6.8.12-1-pvenpm verbose node v20.17.0npm verbose npm v10.8.2npm verbose exit -39npm verbose code -39npm error A complete log of this run can be found in: /root/.npm/_logs/2024-09-06T04_25_52_947Z-debug-0.log
spawn - [07:25:57.150] [Matterbridge:spawn]: child process exited with code 217 and signal null
error - [07:25:57.150] [Matterbridge]: Child process "npm install -g matterbridge-shelly --verbose" exited with code 217 and signal null
spawn - [07:25:57.151] [Matterbridge:spawn]: child process closed with code 217 and signal null
error - [07:25:57.151] [Matterbridge]: Child process "npm install -g matterbridge-shelly --verbose" closed with code 217 and signal null
error - [07:25:57.152] [Matterbridge]: Error installing plugin matterbridge-shelly
info - [07:25:57.155] [PluginManager]: Added plugin matterbridge-shelly
info - [07:25:57.156] [PluginManager]: Loading plugin matterbridge-shelly type
error - [07:25:57.205] [PluginManager]: Failed to load plugin matterbridge-shelly: SyntaxError: The requested module 'matterbridge/cluster' does not provide an export named 'ElectricalEnergyMeasurement'
info - [07:26:35.971] [Matterbridge]: Setting reachability to true for Matterbridge

**Comment by ionutm80** [comment]
I figured it out myself:
manual delete '/usr/lib/node_modules/matterbridge-shelly', restart and reinstall matterbridge-shelly, now it works!

**Comment by Luligu** [comment]
Hi,
is a well known issue with npm that sometime comes out.
Maybe updating node and npm on the host machine can also help.

See https://github.com/Luligu/matterbridge/issues/100
