### ISSUE TITLE
Lost devices after update

### ISSUE THREAD

**Issue by barry74** [Luligu/matterbridge#125]
During the update to 1.5.4 I lost all the matterbridge-shelly devices in Apple Home.
Please fix. I don't want to update again if I loose all devices.
Thanks.

**Comment by Apollon77** [comment]
@barry74 ... and you think that with these details any developer can do/find anything? No log, no information from which version you updated to which ... and and and ... This issue in this form is not really helpful

**Comment by barry74** [comment]
I'm new to matterbridge.. Updated from 1.5.3 -> 1.5.4.
The logfiles are 0 bytes, no information there.
I made backup now, maybe restore will help next time.
Keep on the good work!

**Comment by Luligu** [comment]
Hi,
what other plugins are you using ?
Any other info?
What machine you run on?
Cause we run extensive tests on the updates in all possible conditions before releasing... and no issues were found.
I test deeply AppleHome with a setup of 150 devices...
