### ISSUE TITLE
Unable to control from smartthings since the 1.5.4 update

### ISSUE THREAD

**Issue by dohun0310** [Luligu/matterbridge#126]
I'm using a [SmartThings Hub](https://www.amazon.com/Samsung-SmartThings-Generation-GP-U999SJVLGDA-Automation/dp/B07FJGGWJL). I am using [this plugin](https://github.com/t0bst4r/matterbridge-home-assistant) to control my Home Assistant devices from Smartthings.

After 1.5.4 update, I could see the status of that device in SmartThings, but I couldn't turn it off or turn it on it. I can't able to see any logs from Matterbridge.

I using [this docker image](https://github.com/t0bst4r/matterbridge-home-assistant/pkgs/container/matterbridge-home-assistant) on Synology NAS. I haven't checked, but I can send you the logs from the SmartThings Hub if you'd like.

**Comment by Luligu** [comment]
Hi,
I'm sorry for that, but I cannot help you with that plugin.
It is well known for causing problems, since it doesn't meet the Matterbridge requirements: https://github.com/Luligu/matterbridge/blob/dev/README-DEV.md.
The author unfortunately doesn't want to collaborate.

**Comment by dohun0310** [comment]
There is no problem in 1.5.3, only in 1.5.4. I understand the issue with this plugin, but I don't think it's the reason for this plugin.

**Comment by Luligu** [comment]
If you want to test your controller install Matterbridge following the guidelines (no addons and unsupported plugins) and install the dynamic example plugin. There you have almost all device types and since they are virtual is easy to test if your controller has issues with any of them. As of my knowledge Smart has only issues with color lights (HS or XY).

**Comment by dohun0310** [comment]
I tried Outlet on dynamic example plugin. It also can't control on SmartThings

**Comment by dohun0310** [comment]
`info - [09:41:13.352] [Switch]: Command off called with: undefined`
Attempting to control switch will generate these logs.

**Comment by Luligu** [comment]
It is correct in fact. 
There is no request in command on off toggle.

**Comment by dohun0310** [comment]
I don't understand what you mean about there being no command for off.

**Comment by Luligu** [comment]
The undefined is the request to the command: is correct cause on off toggle have no request, only command.
That part in the dynamic plugin has a bug cause I was porting the plugin for the new api V8 and I left uncommented a part.
Fixed.

BTW if you code in Home Assistant we can try to make a working matterbridge add on if you have time.

**Comment by dohun0310** [comment]
Seriously, you forced me to disable the Home Assistant Addon in 1.5.5, and it's your intention that it doesn't work in 1.5.4? I really don't understand.

**Comment by Luligu** [comment]
Hi,
seriously I don't know what you are talking about...
If you mean this plugin https://github.com/t0bst4r/matterbridge-home-assistant, the author just have to remove the wrong import and wrong dependencies. 
Release 1.5.5 updated to matter 0.10.1 so there is no other solution.
Btw I really love the idea to port to matter the ha devices. Is great.
