### ISSUE TITLE
Run Homebridge concurrently

### ISSUE THREAD

**Issue by twocolddogs** [Luligu/matterbridge#129]
Hey @Luligu - I'm finding matterbridge much more stable for my Shelly devices, it's working really really well. 

But, there are a couple of cool homebridge plugins I'd like to utilise - like https://github.com/maxileith/homebridge-appletv-enhanced 

Is it possible to run matterbridge and Homebridge at the same time on the same machine?

**Comment by Apollon77** [comment]
In theory these should not interfere I would assume, or which issues you expect?

**Comment by Luligu** [comment]
Hi,
thanks for your appreciation.
Unless you use an homebridge shelly plugin, there is no issue at all: this is cause the updates from shellies arrive only to one WebSocket client (the first to connect).
In my production setup I have on the same machine (raspberry pi 5) matterbridge, homebridge, zigbee with docker compose.
If you want my docker compose to take a look let me know.
In homebridge I use Homebridge Security System and Dyson plugins. 
I will try also the one you like.
My best.
