### ISSUE TITLE
The Plug of HEATING_COOLING_UNIT can not run successfully

### ISSUE THREAD

**Issue by sky987654** [Luligu/matterbridge#131]
hi 
When I run the HEATING-COOLING-UNIT type, an error message appears. Can you see why this is happening? thank you very much.
![2d4b8966cd9459ce9f000b047c70210](https://github.com/user-attachments/assets/4b141129-c4ae-4ce4-b7d7-13fc2feb0986)

**Comment by sky987654** [comment]
Can you add an example of HEATING-COOLING-UNIT directly into this? We have tried many times but have been getting errors. Thank you very much.
https://github.com/Luligu/matterbridge-example-accessory-platform

**Comment by Luligu** [comment]
Hi,
sorry but also in the other issue you didn't answer,
What plugin are you using/coding?

This device type will never work cause 

    HEATING_COOLING_UNIT: DeviceTypeDefinition({
        name: "MA-heatcool",
        code: 0x0300,
        deviceClass: DeviceClasses.Simple,
        revision: 2,
        requiredServerClusters: [
            MatterClusters.IdentifyCluster.id,
            MatterClusters.GroupsCluster.id,
            MatterClusters.OnOffCluster.id,
        ],
        optionalServerClusters: [MatterClusters.LevelControlCluster.id, MatterClusters.FanControlCluster.id],
        requiredClientClusters: [MatterClusters.ThermostatCluster.id],
    }),
requires the ThermostatCluster like a cluster client not cluster server.

Cluster clients are not currently supported by matter.js.

**Comment by Luligu** [comment]
Who are you?

**Comment by Apollon77** [comment]
@sky987654 I would propose to read matter specifications of the version you want to support? They are free to download. Then you can "design" the device correctly ...

There is no ThermostatCluster as Client in the specs at all, That needs to be a required ClusterServer. Additionally the device type must not have an OnOffCLient nor LevelControl nor FanControl.

Honestly ... please DO NOT design stuff that way, this is dangerous and invalid in many areas and when the open source developers generate such a bad quality then this might also have effects in how we can use Matter and the openness of Matter as a whole. With such design as you show here you can generate undefined behaviors and issues with Controllers out there and shad a bad light on open source matter development, matterbridge and matter.js!

If you want to develop matter devices then follow the specs or wait until tools like matterbridge offer ways to do this easiely within the specs.

**Comment by Apollon77** [comment]
The current Matter 1.3 specs to not have this device type anymore, so I think it will never be supported by anyone

**Comment by sky987654** [comment]
Sorry, I fell asleep yesterday. I am a matter enthusiast and I particularly enjoy the openness of matter. You wrote very well.

**Comment by sky987654** [comment]
I modified it using this example：https://github.com/Luligu/matterbridge-example-accessory-platform
 I don't quite understand, please forgive me.

**Comment by sky987654** [comment]
By the way, does matter.js have plans to support cluster clients? thank you!

**Comment by Apollon77** [comment]
> By the way, does matter.js have plans to support cluster clients? thank you!

Sure. The think currently is the following: There is NO controller existing at all that would allow you to setup bindings and most real world devices also do not have client clusters ... So currently having them is kind of theoretical topic ...
We plan to also have a controller implementation with UI in matter.js which would allow setting such stuff up, but not yet there

**Comment by sky987654** [comment]
Understood, is there any way to increase the wind speed in the thermostat now? The Apple Homekit app supports adding wind speed to the thermostat. thank you!
