### ISSUE TITLE
Log is flooded with errors

### ISSUE THREAD

**Issue by stony2k** [Luligu/matterbridge#133]
Hi,

I have this problem for some time now. I already reset the commission as well a factory reset. I tried to pair Matterbridge only with Alexa and in another attempt only with Apple. Every time everything is fine at first and after some time the error flood begins. Here is a example:
`[19:17:36.824] [AccessControlManager] Failed access control check for 13/39 and fabricIndex 4, acl= { privilege: 5, authMode: 2, subjects: [ 2973296259 ], targets: null, fabricIndex: 4 } granted privileges= 
[19:17:36.825] [SubscriptionHandler] Error reading event !MA-onofflight(0xd)/BridgedDeviceBasicInformation(0x39)/reachableChanged(0x3): (126) Access to 13/0x39 denied on secure/37135.
  at #assertAccess (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/LegacyInteractionServer.js:51:13)
  at LegacyInteractionServer.readEvent (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/LegacyInteractionServer.js:72:23)
  at SubscriptionHandler.readEvent (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionServer.js:714:55)
  at SubscriptionHandler.sendInitialReport (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/SubscriptionHandler.js:471:43)
  at async LegacyInteractionServer.handleSubscribeRequest (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionServer.js:725:7)
  at async InteractionServerMessenger.handleRequest (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionMessenger.js:128:13)
  at async LegacyInteractionServer.onNewExchange (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/interaction/InteractionServer.js:160:5)
  at async ExchangeManager.onMessage (file:///usr/local/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/protocol/ExchangeManager.js:194:9)`

I am happy to give you all logfiles and information you need. All devices are responsive via Alexa and Apple Homekit running trough Matterbridge.

Matterbridge version 1.5.7

**Comment by Apollon77** [comment]
Hi,

is it only with events like this or also sometimes attributes?

But yes a debug log could help. Enable the "Matter" log on debug please and restart. Then maybe force a devcie to become unreachable .. but also lets see if other things are affected

**Comment by Luligu** [comment]
Hi,
can you please also send us a screenshot of the frontend so we see what plugins you use and the versions?
Also the matterbridge log file could help us.
Thanks.

@Apollon77 matterbridge 1.5.7 is with matter 0.10.3. I have never seen those error messages.

**Comment by Apollon77** [comment]
ACL stuff was last changed in 0.9 at all ... thats why my question is if the issues start somewhen, because then someone would have changed ACL settings or the session is done with the wrong owner nodeid/CAT and tahst why permissio is denied( then wuld be amazon issue) ... or or or ...

**Comment by stony2k** [comment]
I am running Matterbridge in a container in Proxmox with the root user. Here is a screenshot. And the Matterbridge and matter debug log files.

@Apollon77 As far I can see there are only the "Failed access control" errors.

![Bildschirmfoto 2024-09-18 um 18 22 56](https://github.com/user-attachments/assets/cbb28871-bf17-46c4-a2c4-79e538cab6ac)
[matter.log](https://github.com/user-attachments/files/17047581/matter.log)
[matterbridge.log](https://github.com/user-attachments/files/17047592/matterbridge.log)

**Comment by Apollon77** [comment]
Can you please try to remove the pairing with Alexa and pair anew (I know pain to restore all devices afterwards, but in fact I think somehow the ACL got wrong and so thats the reason here. It is the first time I see this and most likely we will also not find out why it happened and by what.

Amazon connects with the peer node Id 0xA828AC46 ... but the ACL entries for this entry are for node 2973296259 aka 0xB138E683 - this can not work. I have no idea right now how that broke other then amazon had a bug (or matter,js ... but then undiscovered one). I will add some more logging for the future (if that happens) to validate that case more easiely, but for now: please remove devices and add again.

**Comment by stony2k** [comment]
I already did this several times. But the result is every time the same and at some point the errors appear again. Would deleting the complete Matterbridge installation bring any new insights for you? Like a factory reset but in a more drastic way.

**Comment by Apollon77** [comment]
In fact then pair anew but let debug log on till it happens again ... then send the full log - ideally some hours before it started to happen and some hours after ... maybe I can pin a reason what forced it to happen

**Comment by stony2k** [comment]
The debug logs are still enabled. Once I am back home (aprox 19:00 German time) I will delete the Alexa pairing and renew it. Then I will wait some time and provide you new logiles.

**Comment by stony2k** [comment]
I just removed Matterbridge from Alex at at first no new errors appeared. But after 9 minutes the flood began again. I downloaded the logfiles and noticed that they exceeded 100 mb and stopped recording new entries since yesterday 18:53. What should I do now to provide you valuable information?

**Comment by Luligu** [comment]
Hi,
you are right: the log on disk stops after 100MB for security reasons.
On small device like rock-s0 there is no space on memory.

**Comment by Apollon77** [comment]
Ok, one last question: Which iOS version is on mobile and on the apple hub?

Else yes I see the issue .... but I do not understand it ... I would add more logging

**Comment by stony2k** [comment]
iOS 18 on mobile and tvOS 17, did not update it to tvOS 18.

Currently I have setup a fresh installation of matterbridge, paired it to Alexa and Apple Home in a second container. No errors so far. The matterbridge installation is paired with Home Assistant to provide you further information. Sadly the error did not appear anymore. So there must be something between the "faulty" matterbridge together with Apple Home. But for now I am happy with not setting up all devices for the 100th time again :D

**Comment by Luligu** [comment]
Hi,
@stony2k Apple updated the firmware yesterday and I had an issue after.
Solved with removing resumption records from the old firmware.
If you can edit a json file I can show you what to remove.

But if you have no more issue with a fresh setup I guess is a confirmation of the problem.

**Comment by stony2k** [comment]
Yes I can edit the json file. Just started the tvOS update before I saw your post :) Thanks for digging into finding a solution :)

**Comment by Luligu** [comment]
If you switch on the docker dev... there we have the latest from matter.js and also a dev from z2m plugin.
I would be happy if you can test it. In that way we have the same version.
Apollon will come out with a solution but first we need to understand.

Wait 30 minutes for docker hub cause 1.5.8-dev.4 is building right now.

**Comment by Luligu** [comment]
## [2.1.17] - 2024-09-20

### Changed

- [matterbridge]: Removed Matterbridge deprecated method to get the child endpoints.
- [package]: Updated dependencies.
- [plugin]: Moved trigger code to matterbridge triggerSwitchEvent.

### Added

- [matterbridge]: Added a check of the current Matterbridge version (required v1.5.5).
- [plugin]: Added configuration of ColorControl cluster features (HS, XY, CT).
- [plugin]: Removed the superset device types.

**Comment by Luligu** [comment]
Built now

**Comment by stony2k** [comment]
I am using a Proxmox LXC container, not docker. Just to avoid missunderstandings. Where can I get the files to replace?

**Comment by Luligu** [comment]
Ah ok sorry I thought you used docker.
Can you install from tgz files? 
If not we can ask @tammeryousef1006 to tell you how...
But then you have to join me on discord cause here I cannot send files.

**Comment by Apollon77** [comment]
mega strange that you now have one contains that works and another one that do not work even with a new commissioning ... wtf ...

I build a new matter.js 0.10.5 currently .. then that should gibe some more logs .. would be great to get that from the one device which is broken

**Comment by stony2k** [comment]
Discord is not problem, please tell me the server.

**Comment by Luligu** [comment]
Contact me but give me your name on discord so 9 know is you

**Comment by stony2k** [comment]
@Luligu I would like to, but I don't see any method to contact you via Github :D Maybe I am too blind 🙈

**Comment by tammeryousef1006** [comment]
try this link :  https://discord.gg/raWywpD4

**Comment by stony2k** [comment]
Joined. My handle stony2k on Discord

**Comment by Luligu** [comment]
1.5.8-dev.5 is building on docker but you will have it from @tammeryousef1006.
It is with matter 0.10.5

**Comment by Apollon77** [comment]
I also got an idea that I check. But having your log too might help and show the same.

**Comment by stony2k** [comment]
Hey @Apollon77: Thanks to the help of @tammeryousef1006 and @Luligu I am testing with the new dev versions 1.5.8-dev.5 and 2.1.17 Zigbee2MQTT plugin.

**Comment by Apollon77** [comment]
Ok, I think I got the issue now ... and thats an apple thing when I am right ...

Commissioning
> [18:25:44.769] [PaseServer] [info] Session 34579 created with udp://fe80::1497:848e:607c:1846%eth0:58305.
...
> [18:25:44.768] [SecureSession] [debug] Created secure PASE session for fabric index undefined secure/34579 idleIntervalMs: 500 activeIntervalMs: 300 activeThresholdMs: 4000 dataModelRevision: 18 interactionModelRevision: 11 specificationVersion: 17039360 maxPathsPerInvoke: 1


This adds this ACL
> [18:25:47.485] [LegacyInteractionServer] [info] ACL updated { fabricIndex: 1, privilege: 5, authMode: 2, subjects: [ 2032937477 ], targets: null }


Then after commisisoning complete the ACL gets updated to ... 
> [18:25:47.746] [CaseServer] [info] session 34580 created with udp://fe80::1497:848e:607c:1846%eth0:58305 for Fabric 00000000A6F9738F(index 1) and PeerNode 00000000792C2A05 (2032937477)
...
> [18:25:47.851] [LegacyInteractionServer] [info] ACL updated { privilege: 5, authMode: 2, subjects: [ 2973296259, 18446744062410031105 ], targets: null, fabricIndex: 1 }

> [18:25:47.865] [InteractionServer] [debug] Received subscribe request from udp://fe80::1497:848e:607c:1846%eth0:58305 on session secure/34580 (keepSubscriptions=true, isFabricFiltered=false)

which means the subject 2032937477 is removed!. The active subscription on 34580 is then "active". From other logs I know that this session is established with another Case tag and so 18446744062410031105 secures that anything works.


Then second fabric gets commissionied via session 34580 which adds a second ACL entry
> [18:25:48.595] [LegacyInteractionServer] [info] ACL updated { privilege: 5, authMode: 2, subjects: [ 2973296259, 18446744062410031105 ], targets: null, fabricIndex: 1 } { fabricIndex: 2, privilege: 5, authMode: 2, subjects: [ 5361656158710164470 ], targets: null }


Next a new session gets created where subject matches ACL subject
> [18:25:52.081] [CaseServer] [info] session 34582 created with udp://fe80::cba:5a38:1c32:b4af%eth0:63289 for Fabric 00000000A6F9738F(index 1) and PeerNode 00000000B138E683 (2973296259)

And this session now removes the additional Case Tag again where the still active 34580 still works on with it's ubscription but it is active, so all good

> [18:25:52.101] [LegacyInteractionServer] [info] ACL updated { privilege: 5, authMode: 2, subjects: [ 2973296259 ], targets: null, fabricIndex: 1 } { fabricIndex: 2, privilege: 5, authMode: 2, subjects: [ 5361656158710164470 ], targets: null }

Session 34582 now also creates a subscription ... so we have 2 running

(we ignore the 2 Acl entries seen in the logs 18:25 because other unrelated bug ...)

Then  the subscription on 34580 dies because of no ack anymore
> [19:59:05.084] [SubscriptionHandler] [error] Sending update failed 3 times in a row, canceling subscription 2406690772 and let controller subscribe again.
[19:59:05.086] [SecureSession] [debug] Removed subscription 2406690772 from secure/34580

Also so far so good.

But now the following happens:
> [19:59:05.084] [SubscriptionHandler] [error] Sending update failed 3 times in a row, canceling subscription 2406690772 and let controller subscribe again.
[19:59:05.086] [SecureSession] [debug] Removed subscription 2406690772 from secure/34580
...
[21:34:10.055] [CaseServer] [info] session 34583 resumed with udp://fe80::1497:848e:607c:1846%eth0:58305 for Fabric 00000000A6F9738F(index 1) and PeerNode 00000000792C2A05 (2032937477)

so the resumption of the session here is done with the "old" node id which has no acl entry anymore because was removed. Even if it would have the special subject 18446744062410031105 (which is not logged) it would not work because also removed. This means that this subscription can only go wrong what it does with
> [21:34:11.708] [InteractionServer] [info] Sending status response 128 for interaction error: (128) Subscription failed because no attributes or events are matching the query

but this is then retried by controller anytime
> [21:34:11.724] [InteractionServer] [debug] Received subscribe request from udp://fe80::1497:848e:607c:1846%eth0:58305 on session secure/34583 (keepSubscriptions=true, isFabricFiltered=false)

**Comment by Luligu** [comment]
@stony2k can you update us please?

**Comment by stony2k** [comment]
@Apollon77 Wow nice work investigating the issue in such detail.
@Luligu No errors so far. But to be sure I will pair Homekit once more to the "old faulty" matterbridge. For the sake of sience to restore all items again :D

**Comment by stony2k** [comment]
@Apollon77 would you like to join is in Discord for live diagnostics?

**Comment by Apollon77** [comment]
very short yes ... where?

**Comment by stony2k** [comment]
https://discord.gg/raWywpD4

**Comment by Apollon77** [comment]
Ok, I think we can close here @Luligu
