### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by kskenyon** [Luligu/matterbridge#14]
Has anyone developed a working docker-compose.yml ?

**Comment by Luligu** [comment]
Hi,docker is still under test.It will be available in the next release On 23 Apr 2024, at 22:46, kskenyon ***@***.***> wrote:﻿
Has anyone developed a working docker-compose.yml ?

**Comment by kskenyon** [comment]
Need to specify ports in docker-compose.yml

**Comment by Luligu** [comment]
HI,
network_mode: host

**Comment by kskenyon** [comment]
That only works if you use a browser on the docker server.  I run headless.
