### ISSUE TITLE
Install self-signed SSL cert

### ISSUE THREAD

**Issue by jedis00** [Luligu/matterbridge#144]
Hello,

Are there directions on how to install a self-signed SSL cert? I've moved the UI to port 80 for now, but would like to move to 443 and install my cert and key.

Thanks!

**Comment by Luligu** [comment]
Hi,
I provided a small guide:

https://github.com/Luligu/matterbridge/blob/dev/README.md#how-to-enable-https-for-the-frontend

My best.
