### ISSUE TITLE
Will not start up for me

### ISSUE THREAD

**Issue by livefeed** [Luligu/matterbridge#146]
Hello, I can't get Matterbridge to start up - my log is as follows;

 Add-on version: 2.9.0-PSA-121
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 12 (bookworm)  (amd64 / qemux86-64)
 Home Assistant Core: 2024.10.0b1
 Home Assistant Supervisor: 2024.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
#############################
CURRENT CONFIGURATION:
{
  "homeAssistant": {
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
    "url": "http://supervisor/core",
    "accessToken": "a759d8232c69d5027ee98aa10b43b048ece64a25aed14a4c566c028ee4cb1f25f849e9e17416ebb32f7522d748638b361c22527ee640730c",
    "matcher": {
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
      "includeDomains": [],
      "excludeDomains": [],
      "includePatterns": [],
      "excludePatterns": [],
      "includeLabels": [],
      "excludeLabels": [],
      "includePlatforms": [],
      "excludePlatforms": []
    }
  },
  "overrides": {
    "domains": {},
    "entities": {}
  }
}
#############################
CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/d01917a070027b55bce538a96fa2004f061de6fe1644f402a321c6db8c71b9ba does not look like a valid storage file!
CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/d01917a070027b55bce538a96fa2004f061de6fe1644f402a321c6db8c71b9ba does not look like a valid storage file!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Luligu** [comment]
Hi,
that means the storage got ruined for some reason (hardware or software issues).
You can replace the storage directory with the backup or just delete the storage directory and start over.
In ha you find it in /addons/matterbrige/.matterbridge.
Let me know if you need help with that.
My best

**Comment by livefeed** [comment]
Thank you, that did the trick!

I can't get it to update though (Update v.1.5.0 to v.1.5.9) hit update but does not do it.

**Comment by Luligu** [comment]
Great!.
All your issues are caused by the addon you are using...
Read this please https://github.com/Luligu/matterbridge/blob/dev/README.md#advanced-configurations

Run matterbridge as an home assistant add-on with the official add-on
[Advanced configurations](https://github.com/Luligu/matterbridge-home-assistant-addon)

Other Home Assistant Community Add-ons
The other Home Assistant Community Add-ons and plugins are not verified to work with Matterbridge. I strongly advise against using them. If you do use them and encounter an issue (which is likely because some do not meet the Matterbridge guidelines), please do not open an issue in the Matterbridge repository.

My best.
