### ISSUE TITLE
matterbridge.json 0 length

### ISSUE THREAD

**Issue by kskenyon** [Luligu/matterbridge#148]
Matterbridge will run for a day then it will fail.  My .matterbridge/matterbridge.json file is zero bytes.  If I replace it with matterbridge.backup.json it runs OK for a while then fails again.  

What would cause the configuration file matterbridge.json to be zero length?

RaspberryPi with docker.  Running docker-compose.

services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - "${HOME}/matterbridge:/root/matterbridge" # Mounts the Matterbridge plugin directory
      - "${HOME}/.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory

**Comment by Luligu** [comment]
Hi,
I can imagine is an hardware issue with your SD card.
If you want more help keep the debug log on file for matterbridge enabled and when it happens again send me the log. 
The matterbridge.json file is the matter storage and should not be written so many times after the initial commissioning. 
Any other useful information about your setup ?
My best

**Comment by kskenyon** [comment]
Running from an external SSD drive.  Works good.

Where do I find the log if the UI is down?

Seems like something weird is happening with the docker setup.  Something is overwriting the matterbridge.json file with an empty file.  Is it trying to reinitialize on some frequency but not coordinated with a running container?

Kevin

**Comment by kskenyon** [comment]
It did it again overnight. Here is the log.  Don’t see anything interesting.  I also have to re-pair matterbridge to the Home app or it just shows No Response for this plugin.  Only running the demo dynamic plugin on this installation.  I have another more complex installation at my other house.  Can’t check that right now.  

￼
Kevin

**Comment by Luligu** [comment]
Hi,
sorry but I cannot see the log...

**Comment by kskenyon** [comment]
￼
