### ISSUE TITLE
Issue with Home Assistant plugin installation while running Matterbridge using Docker Compose

### ISSUE THREAD

**Issue by amrutprabhu** [Luligu/matterbridge#149]
Hi,

First of all, thanks a lot for this matter bridge. You are making things easier to share across many ecosystems. 

I am currently trying to run this using docker compose as mentioned here: https://github.com/Luligu/matterbridge/blob/main/README-DOCKER.md

This is my exact config. 
```
services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - "./Matterbridge:/root/Matterbridge" # Mounts the Matterbridge plugin directory
      - "./.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory
```

Now It all starts properly, but when I try to install the Home Assistant Plugin by typing "matterbridge-home-assistant", it downloads the plugin and installs it. But the plugin manager fails to add it. 

here are the logs I got

```
spawn - [17:22:34.706] [Matterbridge:spawn]: npm verbose os Linux 5.15.0-117-genericnpm verbose node v22.9.0npm verbose npm v10.8.3
spawn - [17:22:34.706] [Matterbridge:spawn]: npm verbose exit 0npm info ok
spawn - [17:22:34.724] [Matterbridge:spawn]: child process exited with code 0 and signal null
spawn - [17:22:34.724] [Matterbridge:spawn]: child process closed with code 0 and signal null
notice - [17:22:34.724] [Matterbridge]: Package matterbridge-home-assistant installed correctly
info - [17:22:34.725] [Matterbridge]: Plugin matterbridge-home-assistant installed. Full restart required.
error - [17:22:34.726] [PluginManager]: Found @project-chip packages "@project-chip/matter.js" in plugin devDependencies.
error - [17:22:34.726] [PluginManager]: Please open an issue on the plugin repository to remove them.
error - [17:22:34.726] [PluginManager]: Failed to add plugin matterbridge-home-assistant: package.json not found
Matterbridge - Restarting matterbridge...
info - [17:25:37.918] [Matterbridge]: shutting down...

``` 

I running this on x86 machine. 

Can you tell me why it cannot find the `package.json` as per the logs?

**Comment by Luligu** [comment]
Hi,
That plugin has always had a lot of issues. 
I tried to collaborate with the author cause the idea behind his project is brilliant but he doesn't want to collaborate so...
I will write an home assistant plugin myself but right now I'm really busy with Shelly so it will not be soon.

**Comment by dankocrnkovic** [comment]
I have been trying for hours to make Home Assistant addon working. After install, devices list is empty, and commisioning to google home, just creates one offline device.
So as I understand now, HA plugin is not working currently? 
I thougth internaly HA Addon has HA plugin enbled. Can you clarify this?

**Comment by Luligu** [comment]
That plugin will never load and work unless the author modify it accordingly to the matterbridge guidelines:
https://github.com/Luligu/matterbridge/blob/main/README-DEV.md.

It would take no more then a few seconds. But I understand he want to do something on his own.
