### ISSUE TITLE
Docker Endless restart loop.  Missing file.

### ISSUE THREAD

**Issue by kskenyon** [Luligu/matterbridge#15]
sudo journalctl -f -u containerd
Apr 25 16:52:06 pi3 containerd[1010]: time="2024-04-25T16:52:06.114888515-04:00" level=warning msg="cleanup warnings time=\"2024-04-25T16:52:06-04:00\" level=info msg=\"starting signal loop\" namespace=moby pid=22000 runtime=io.containerd.runc.v2\n"
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.183769555-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.184311455-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.184375454-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.185146481-04:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 pid=22344 runtime=io.containerd.runc.v2
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.381230782-04:00" level=warning msg="error from *cgroupsv2.Manager.EventChan" error="failed to add inotify watch for \"/sys/fs/cgroup/system.slice/docker-3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217.scope/memory.events\": no such file or directory"
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.438649971-04:00" level=info msg="shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.439030651-04:00" level=warning msg="cleaning up after shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 namespace=moby
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.439094853-04:00" level=info msg="cleaning up dead shim"
Apr 25 16:53:06 pi3 containerd[1010]: time="2024-04-25T16:53:06.468233201-04:00" level=warning msg="cleanup warnings time=\"2024-04-25T16:53:06-04:00\" level=info msg=\"starting signal loop\" namespace=moby pid=22386 runtime=io.containerd.runc.v2\n"
Apr 25 16:54:08 pi3 containerd[1010]: time="2024-04-25T16:54:08.041648455-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Apr 25 16:54:08 pi3 containerd[1010]: time="2024-04-25T16:54:08.042233466-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Apr 25 16:54:08 pi3 containerd[1010]: time="2024-04-25T16:54:08.042306039-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Apr 25 16:54:08 pi3 containerd[1010]: time="2024-04-25T16:54:08.043167231-04:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 pid=22721 runtime=io.containerd.runc.v2
Apr 25 16:54:08 pi3 containerd[1010]: time="2024-04-25T16:54:08.878390714-04:00" level=warning msg="error from *cgroupsv2.Manager.EventChan" error="failed to add inotify watch for \"/sys/fs/cgroup/system.slice/docker-3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217.scope/memory.events\": no such file or directory"
Apr 25 16:54:09 pi3 containerd[1010]: time="2024-04-25T16:54:09.423631174-04:00" level=info msg="shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217
Apr 25 16:54:09 pi3 containerd[1010]: time="2024-04-25T16:54:09.479496544-04:00" level=warning msg="cleaning up after shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 namespace=moby
Apr 25 16:54:09 pi3 containerd[1010]: time="2024-04-25T16:54:09.479554673-04:00" level=info msg="cleaning up dead shim"
Apr 25 16:54:09 pi3 containerd[1010]: time="2024-04-25T16:54:09.510272977-04:00" level=warning msg="cleanup warnings time=\"2024-04-25T16:54:09-04:00\" level=info msg=\"starting signal loop\" namespace=moby pid=22764 runtime=io.containerd.runc.v2\n"
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.621137720-04:00" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.621646658-04:00" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.621713268-04:00" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.622509739-04:00" level=info msg="starting signal loop" namespace=moby path=/run/containerd/io.containerd.runtime.v2.task/moby/3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 pid=23095 runtime=io.containerd.runc.v2
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.836823972-04:00" level=warning msg="error from *cgroupsv2.Manager.EventChan" error="failed to add inotify watch for \"/sys/fs/cgroup/system.slice/docker-3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217.scope/memory.events\": no such file or directory"
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.889898394-04:00" level=info msg="shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.890086484-04:00" level=warning msg="cleaning up after shim disconnected" id=3db9f248d6a14f9a83dcfef5f619edecfee6b20fca2818bd083d33da21191217 namespace=moby
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.890177798-04:00" level=info msg="cleaning up dead shim"
Apr 25 16:55:09 pi3 containerd[1010]: time="2024-04-25T16:55:09.923019441-04:00" level=warning msg="cleanup warnings time=\"2024-04-25T16:55:09-04:00\" level=info msg=\"starting signal loop\" namespace=moby pid=23140 runtime=io.containerd.runc.v2\n"

**Comment by Luligu** [comment]
Hi,
thank you for your message and the log.
Without context I cannot understand.
I need some more information...
What machine are you using? What version of docker?

**Comment by kskenyon** [comment]
RaspberryPi4
 
Linux pi3 6.1.28-v8+ #1651 SMP PREEMPT Wed May 17 14:34:39 BST 2023 aarch64 GNU/Linux

$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.26.1)

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 12
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1
 runc version: 1.1.5+ds1-1
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.28-v8+
 Operating System: Raspbian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.704GiB
 Name: pi3
 ID: ZN5P:JLJE:TZNH:DH4Y:NABV:GUUL:NUKS:AYIT:3IVJ:IWKH:H54K:KCLF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support


Linux pi3 6.1.28-v8+ #1651 SMP PREEMPT Wed May 17 14:34:39 BST 2023 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have new mail.
Last login: Fri Apr 26 16:17:27 2024
***@***.***:~ $ uname -a
Linux pi3 6.1.28-v8+ #1651 SMP PREEMPT Wed May 17 14:34:39 BST 2023 aarch64 GNU/Linux
***@***.***:~ $ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.26.1)

Server:
 Containers: 6
  Running: 2
  Paused: 0
  Stopped: 4
 Images: 12
 Server Version: 20.10.24+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.6.20~ds1-1
 runc version: 1.1.5+ds1-1
 init version: 
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.1.28-v8+
 Operating System: Raspbian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.704GiB
 Name: pi3
 ID: ZN5P:JLJE:TZNH:DH4Y:NABV:GUUL:NUKS:AYIT:3IVJ:IWKH:H54K:KCLF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support

***@***.***:~/matterbridge $ less docker-compose.yml 

services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - plugin:/pi/home/matterbridge # Volume: matterbridge_plugin
      - storage:/pi/home/.matterbridge # Vloume: matterbridge_storage

volumes:
  plugin:
  storage:
docker-compose.yml (END)

**Comment by Luligu** [comment]
Hi,
thanks you for your replay.
I see nothing that gives me any idea about the reason.
If you have time I try with image: luligu/matterbridge:dev that is a manifest list image.

**Comment by Luligu** [comment]
Last thing what is the architecture of your machine?
The matterbridge:latest was the first beta and supports only arm64 but if your machine is linux/arm/v7 cannot work.
luligu/matterbridge:dev is a manifest list image and should work.
Let me know

**Comment by kskenyon** [comment]
aarch64=arm64. Running raspberry pi OS 64 bit. Running v8 OS.

Switched to :dev, no difference.

failed to add inotify watch for \"/sys/fs/cgroup/system.slice/docker-c53dfc7c79d958eb0609b260e431186202755d51702f6db59d2b7c2952481219.scope/memory.events\": no such file or directory"

Can’t even add memory.events manually due to permissions.  It dies after this error.  Don’t know docker enough to know what inotify watch is.

**Comment by kskenyon** [comment]
Still getting the memory.events error but it started running OK after a couple of restarts.  port 8283 is working remotely for the UI, too.

Thanks for the amazing work on this.

**Comment by Luligu** [comment]
Hi,
thank for the replay.
We use docker compose with arm64 and amd64 without any problem.
I use it on a raspberrypi 4 like yours too and everything is correct.
May try to update or reinstall it...
Sorry but I don't know how to help you.
Or run Matterbridge standalone or with systemctl.
