### ISSUE TITLE
Matterbridge + NS Panel Pro or Tuya

### ISSUE THREAD

**Issue by akadlec** [Luligu/matterbridge#150]
Is anybody using this bridge with NS Panel PRO as hub or with Tuya? Just installer matterbridgei witch shelly plugin to check it out. Bridge is running, Shellies are discovered. Once I try to pair with ewelink it look ok, bridge is visible, also devices, but devices are offline and the NS panel keeps restarting. With the Tuya I'm not able to pair.

**Comment by tammeryousef1006** [comment]
hi there ,
regarding NS Panel pro which is ewelink you could pair matterbridge with limited devices , I tested it with switches and plugs and it was fine , but I face issue if ever I will connect more than 10 devices .
regarding Tuya hub is still not supporting matterbridge function even you can pair it , I have also ihost which act as matterbridge for ewelink and I did try to pair it to tuya and msg came up shows as not supported  .

**Comment by tammeryousef1006** [comment]
![Screenshot_20241019_020634_Smart Life](https://github.com/user-attachments/assets/e5c50114-661a-434d-a3fb-e712ca3cc2b5)

**Comment by akadlec** [comment]
Hi @tammeryousef1006 so I whitelisted only 4 Shellies - 2x gen 1 shelly 1, 1x gen 1 rgbw and 1x gen 3 1pm. I was able to pair them/bridge with ewelink and ns panel. After pairing finished they were added like switches but offline. After ns panel reboot they went online, but are not represented as switches.

![IMG_1235](https://github.com/user-attachments/assets/b3373dbd-be54-4a3c-9679-948b079d2fb5)

**Comment by tammeryousef1006** [comment]
try to add them to each category at shelly config before pairing , and for me the RGB didn't play well with ewlink so blacklist it please 

![config](https://github.com/user-attachments/assets/3c34ec26-02a6-4f85-9d50-e27fa53348eb)

**Comment by tammeryousef1006** [comment]
i test already and i got your point , the devices being detected as button not as switches , kindly go to config of shelly and disable two options 1- exposeinput 2- exposeinputevent , after that try to pair  , I already tested it after disabling both options and switches shows up correctly 

![Screenshot_20241019_110328_eWeLink](https://github.com/user-attachments/assets/02187454-3313-436e-b4af-3ce4a01d54ba)

**Comment by tammeryousef1006** [comment]
![event](https://github.com/user-attachments/assets/c75f1c21-8cb6-41a6-aeba-78d763be8889)
![input](https://github.com/user-attachments/assets/5cb0c631-f5f3-46b5-a7bb-a3cf0398a7dc)

**Comment by akadlec** [comment]
Hmm maybe the problem with tuya is caused by fact that tay support single devices only? And only major device types like switches lights and sensors.

**Comment by tammeryousef1006** [comment]
tuya doesnt support adding matterbridge types yet , i already upload before a screenshot of adding another matterbridge to tuya

**Comment by akadlec** [comment]
so maybe add support to split devices into separate matter devices could be way?

**Comment by tammeryousef1006** [comment]
@Luligu what you think ?

**Comment by Luligu** [comment]
> so maybe add support to split devices into separate matter devices could be way?

What do you mean ?

**Comment by akadlec** [comment]
Now it works as bridge, so I act as bridge with X subdevices. Maybe it could be a way to have option to not create a bridge, but have each device as separate matter device. Eg. each shelly device would have its QR code, port etc.

**Comment by Luligu** [comment]
I imagine they will support bridges in the future...
Exposing single devices with their own QR is not practical but an interesting idea.

**Comment by Apollon77** [comment]
Yes possible also with matter.js (also multiple bridges btw9 ... but keep in mind also this has a "cost": Amazon ist currently only searching for port 5540 ... so while Apple, Google and Tuya might work with multiple devices per host, Alexa will only find the one on port 5540!

**Comment by akadlec** [comment]
I know there will be cons, but if this option will bring matter to other platform could be a big pro. By default keep the matterbridge as bridge and in config have ability to switch it to "separate" mode with some "warning" for users

**Comment by Luligu** [comment]
Then also to consider how many devices you have...

**Comment by akadlec** [comment]
yes, of course. In my case it could be only few devices which I want to bridge to tuya
