### ISSUE TITLE
How to configure Home assistant devices?

### ISSUE THREAD

**Issue by DanSega1** [Luligu/matterbridge#154]
I installed the container with CasaOS and want to expose my home assistant devices, but it looks like there isn't plugin for it in the list, there is a documentation how to add it manually?
The log:
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/9a528ea3-9b55-4094-9fad-77d45dd9a40f">

**Comment by Luligu** [comment]
Hi,
sorry but that plugin doesn't work.

I will publish a working one but it is still in alpha.
