### ISSUE TITLE
Update v.1.5.0 to v.1.6.1 --- Not working

### ISSUE THREAD

**Issue by sierralx** [Luligu/matterbridge#164]
It says "New Matterbridge version available, click to install"

Logs shows:
Matterbridge - Updating matterbridge...
info - [21:28:35.461] [Matterbridge]: Updating matterbridge...

But nothing happen.

![SCR-20241106-spyc](https://github.com/user-attachments/assets/7e6870ab-bf03-4bde-bac3-d28403d949b4)

**Comment by Luligu** [comment]
You are using the add-on not from matterbridge official add-on
