### ISSUE TITLE
Cannot add MatterBridge to Alexa

### ISSUE THREAD

**Issue by korguatimbale** [Luligu/matterbridge#167]
Greetings,

I cannot add Matter to Alexa.  I am using an Android phone on the same VLAN as Matterbridge v.1.5.0, running on 6.6.54-haos.  Plugin version is 2.9.0-PSA

Seems the clue might be in these two lines

error - [14:28:21.713] [InteractionMessenger]: RetransmissionLimitReachedError at MessageExchange.retransmitMessage (file:///usr/local/l ... eExchange.js:276:36) at TimerNode.callback (file:///usr/local/l ... eExchange.js:296:20) at Timeout._onTimeout (file:///usr/local/l ... e/TimeNode.js:50:12) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)
error - [14:28:21.714] [ExchangeManager]: The previous message has not been acked yet, cannot send a new message. at MessageExchange.send (file:///usr/local/l ... eExchange.js:184:13) at InteractionServerMessenger.send (file:///usr/local/l ... nMessenger.js:61:26) at InteractionServerMessenger.sendStatus (file:///usr/local/l ... nMessenger.js:64:17) at InteractionServerMessenger.handleRequest (file:///usr/local/l ... Messenger.js:163:20) at async LegacyInteractionServer.onNewExchange (file:///usr/local/l ... tionServer.js:139:5) at async ExchangeManager.onMessage (file:///usr/local/l ... ngeManager.js:173:9)

Full disclosure - completely new to all this HA & Matter but have solid IT skills in other areas.

info - [14:09:31.549] [Matterbridge]: The commissioning server on port 5540 for Matterbridge is not commissioned. Pair it scanning the QR code:
info - [14:09:31.550] [Matterbridge]: Matterbridge qrPairingCode: MT:Y.K904QI140XRM4KD10 Manual pairing code: 20234239177
info - [14:10:01.551] [PluginManager]: Configuring plugin matterbridge-home-assistant type DynamicPlatform
notice - [14:10:01.551] [PluginManager]: Configured plugin matterbridge-home-assistant type DynamicPlatform
info - [14:10:26.820] [PaseServer]: Received pairing request from udp://10.0.1.103:5541.
info - [14:10:26.970] [PaseServer]: Session 55892 created with udp://10.0.1.103:5541.
info - [14:10:26.977] [SessionManager]: End insecure session insecure/9230448183719543383
info - [14:10:31.551] [Matterbridge]: Setting reachability to true for Matterbridge
info - [14:10:42.632] [MatterDevice]: Announce done fabric: 293713883433312706 fabricIndex: 1
info - [14:10:42.634] [AttributeServer]: Set remote value for fabric scoped attribute "acl" to [{"fabricIndex":1,"privilege":5,"authMode":2,"subjects":["18446744060825763882"],"targets":null}]
info - [14:10:42.636] [LegacyInte~ionServer]: ACL updated { fabricIndex: 1, privilege: 5, authMode: 2, subjects: [ 18446744060825763882 ], targets: null }
info - [14:10:42.637] [Operationa~alsServer]: addNoc success, adminVendorId 4631, caseAdminSubject 18446744060825763882
info - [14:10:42.855] [CaseServer]: Received pairing request from udp://10.0.1.103:5541
info - [14:10:42.928] [Matterbridge]: Active session changed on fabric 1 id 293713883433312706 vendor 4631 (Alexa) for Matterbridge { name: 'secure/55893', nodeId: 293748192894142336, peerNodeId: 293713887647272945, fabric: { fabricIndex: 1, fabricId: 293713883433312706, nodeId: 293748192894142336, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: '' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1732025442927, lastActiveTimestamp: 1732025442927, numberOfActiveSubscriptions: 0 }
info - [14:10:42.929] [CaseServer]: session 55893 created with udp://10.0.1.103:5541 for Fabric 04139A6CD2DE4780(index 1) and PeerNode 04137B3982D08FF1
info - [14:10:42.940] [SessionManager]: End insecure session insecure/1409951075744124027
error - [14:10:46.787] [InteractionMessenger]: RetransmissionLimitReachedError at MessageExchange.retransmitMessage (file:///usr/local/l ... eExchange.js:276:36) at TimerNode.callback (file:///usr/local/l ... eExchange.js:296:20) at Timeout._onTimeout (file:///usr/local/l ... e/TimeNode.js:50:12) at listOnTimeout (node:internal/timers:569:17) at process.processTimers (node:internal/timers:512:7)
error - [14:10:46.788] [ExchangeManager]: The previous message has not been acked yet, cannot send a new message. at MessageExchange.send (file:///usr/local/l ... eExchange.js:184:13) at InteractionServerMessenger.send (file:///usr/local/l ... nMessenger.js:61:26) at InteractionServerMessenger.sendStatus (file:///usr/local/l ... nMessenger.js:64:17) at InteractionServerMessenger.handleRequest (file:///usr/local/l ... Messenger.js:163:20) at async LegacyInteractionServer.onNewExchange (file:///usr/local/l ... tionServer.js:139:5) at async ExchangeManager.onMessage (file:///usr/local/l ... ngeManager.js:173:9)
info - [14:11:46.984] [FailsafeContext]: Failsafe timer expired, Reset fabric builder.
info - [14:11:47.001] [SessionManager]: End CASE session secure/55893
info - [14:11:47.004] [MatterDevice]: All announcements expired
info - [14:11:47.020] [SecureSession]: Register Session secure/55892 to send a close when exchange is ended.
info - [14:11:47.138] [SessionManager]: End PASE session secure/55892
info - [14:11:47.272] [CommissioningServer]: The device was factory reset and restarted.
warn - [14:11:47.272] [Matterbridge]: Commissioning removed from fabric 1 for Matterbridge. Resetting the commissioning server ...
info - [14:11:47.414] [MatterDevice]: All announcements expired
info - [14:11:47.464] [CommissioningServer]: The device was factory reset and restarted.
warn - [14:11:47.464] [Matterbridge]: Restart to activate the pairing for Matterbridge.

**Comment by Luligu** [comment]
Hi,
thanks for your interest in Matterbridge.
Please read the first lines of the matterbridge README about the unofficial and not working packages that you are using….
They didn’t work in the past and will never work in the future unless the author decides to follow the Matterbridge  and Matter guidelines and requirements.
You can move to the official add-on if you want.

**Comment by korguatimbale** [comment]
Thank you, I had not fully understood the differences between the packages.  I was following this article https://smarthomescene.com/guides/exposing-home-assistant-entities-as-matter-devices/ 

I have installed the official add-on now and bang, it added to Alexa with no fuss.

Is there a trick to getting the HA devices / entities added to Matterbridge?

**Comment by Luligu** [comment]
Hi,
sure Matterbridge works correctly is only that other package that is not working. Unfortunately it uses the Matterbridge name...

For adding the ha devices to Matterbridge you have to wait a little cause my plugin is still in alpha and I don't have time right now cause I'm working with Shelly and migrating all Matterbridge code to Matter.js new API....

What devices you need to add ? Switches, lights, doorLock and fan are ready... but not published.

**Comment by korguatimbale** [comment]
It was for LG/Samsung TVs, Lyrion Music Server and Plex.  Lights and plugs are all Alexa compatible.

**Comment by Luligu** [comment]
Ok no support on Matter controllers so far that...
