### ISSUE TITLE
Alexa supports lightsensors

### ISSUE THREAD

**Issue by IvoGruber** [Luligu/matterbridge#168]
Alexa supports matter lightsensors. Seen with Shelly Blu DoorWindow via matterbridge-shelly plugin. So you can adjust the Readme and remove the line stating that it does not support it.

**Comment by Luligu** [comment]
Can you send me a photo please ?

**Comment by IvoGruber** [comment]
![Screenshot_20241126_044741_Amazon Alexa](https://github.com/user-attachments/assets/66f3b56d-d623-4c86-b3ba-f2d1d3511404)
![Screenshot_20241126_044647_Amazon Alexa](https://github.com/user-attachments/assets/da32f562-798c-4be3-9ac8-91c17f3024b5)
![Screenshot_20241126_044632_Amazon Alexa](https://github.com/user-attachments/assets/c0021575-1e73-498b-b157-ece430d0e8ed)
