### ISSUE TITLE
AC - HeaterCooler cannot be created 

### ISSUE THREAD

**Issue by aryelevin** [Luligu/matterbridge#183]
Hi,

I'm using v1.6.5 of this project and I couldn't create an AC device.
It claims it needs Thermostat client cluster which I don't have data on how to create.
In addition, it seems client clusters isn't supported.
Am I missing something?

Thanks in advance

**Comment by Luligu** [comment]
Hi,
thank you for your interest.
Who claims that it needs a client cluster?

The thermostatDevice rev 3
![image](https://github.com/user-attachments/assets/e3e71290-dd9b-412a-9339-ca58e65779ff)
doesn't require any client clusters. 

Only Identifiy and Thermostat. all the others are optional.

The client clusters are still not supported by matter.js and btw no controllers support them at the moment.

Check the code in dynamic example plugin if want to see a thermostat. Or in zigbee / shelly plugin if you want to see the 3 different types of thermostat (Auto, Heating only, Cooling only.

**Comment by aryelevin** [comment]
Thanks for your response.
I'm talking about heat cool device which is basically air conditioners (not thermostats).
I've implemented it on HomeKit using homebridge, so I'm trying to convert my project and use matterbridge for it.
On DeviceTypes.js line 644 you can see the HEATING_COOLING_UNIT type which do have a required requiredClientClusters for some reason.
Any ideas?

**Comment by aryelevin** [comment]
It doesn't show up on apple, I wonder if the problem is that apple isn't supporting it or its a coding problem...
Any suggestion on how to validate?

**Comment by Luligu** [comment]
In general Apple Home supports Matter 1.1.

Plus airQualitySensor without the mesurements.
Minus pressureSensor.

If you load all example plugins and test plugin you have an idea of what devices and cluster are supported.

https://github.com/Luligu/matterbridge/blob/main/CHANGELOG.md#discord

**Comment by Luligu** [comment]
> It doesn't show up on apple, I wonder if the problem is that apple isn't supporting it or its a coding problem... Any suggestion on how to validate?

Send me a link to your repo if you want me to take a look, but as I told you is probably not supported. But Fan and Thermostat clusters are fully supported and of course Humidity and Temperature, so you can just compose it with them. Is not very different the result.

Check the Thermostat in dynamic example plugin to have an idea of how to do it..

**Comment by aryelevin** [comment]
I'm currently using your dynamic platform example for my research and pre-programming work plan.
Here's the code:
In platform.js:
```
// Create a ac device
        this.ac = await this.createMutableDevice([airConditioner, bridgedNode], { uniqueStorageKey: 'AirConditioner' }, this.config.debug);
        this.ac.log.logName = 'AC';
        this.ac.createDefaultIdentifyClusterServer();
        this.ac.createDefaultGroupsClusterServer();
        this.ac.createDefaultOnOffClusterServer();
        this.ac.createDefaultBridgedDeviceBasicInformationClusterServer('AC', '0x96382164', 0xfff1, 'Matterbridge', 'Matterbridge AC', parseInt(this.version.replace(/\D/g, '')), this.version === '' ? 'Unknown' : this.version, parseInt(this.matterbridge.matterbridgeVersion.replace(/\D/g, '')), this.matterbridge.matterbridgeVersion);
        this.ac.createDefaultThermostatClusterServer(20, 18, 22);
        this.ac.createDefaultFanControlClusterServer(FanControl.FanMode.Off);
        await this.registerDevice(this.ac);
        this.bridgedDevices.set(this.ac.deviceName ?? '', this.ac);
        this.ac.addCommandHandler('identify', async ({ request: { identifyTime } }) => {
            this.ac?.log.info(`Command identify called identifyTime:${identifyTime}`);
        });
        this.ac.subscribeAttribute(ThermostatCluster.id, 'systemMode', async (value) => {
            const lookupSystemMode = ['Off', 'Auto', '', 'Cool', 'Heat', 'EmergencyHeat', 'Precooling', 'FanOnly', 'Dry', 'Sleep'];
            this.ac?.log.info('Subscribe systemMode called with:', lookupSystemMode[value]);
        }, this.ac.log, this.ac);
        this.ac.subscribeAttribute(ThermostatCluster.id, 'occupiedHeatingSetpoint', async (value) => {
            this.ac?.log.info('Subscribe occupiedHeatingSetpoint called with:', value / 100);
        }, this.ac.log, this.ac);
        this.ac.subscribeAttribute(ThermostatCluster.id, 'occupiedCoolingSetpoint', async (value) => {
            this.ac?.log.info('Subscribe occupiedCoolingSetpoint called with:', value / 100);
        }, this.ac.log, this.ac);
```


In matterbridgeDeviceTypes.js:

```
// Remark: may have a temperature sensor and a humidity sensor device.
export const airConditioner = DeviceTypeDefinition({
    name: 'MA-airConditioner',
    code: 0x72,
    deviceClass: DeviceClasses.Simple,
    revision: 2,
    requiredServerClusters: [Identify.Cluster.id, OnOff.Cluster.id, Thermostat.Cluster.id],
    optionalServerClusters: [Groups.Cluster.id, /* Scenes.Cluster.id,*/ FanControl.Cluster.id, ThermostatUserInterfaceConfiguration.Cluster.id, TemperatureMeasurement.Cluster.id, RelativeHumidityMeasurement.Cluster.id],
});
```

I want to use AC and not thermostat as in Home app its much easier to turn the AC on/off (Just tap the temperature point on the accessory tile, while on thermostat you have to open the device view and switch the operation mode to off or whatever mode. basically, there's no on/off cluster, only operation mode which have "off" mode and it doesn't remember the last "on" mode).

Thanks in advance

**Comment by Luligu** [comment]
Ok I will make a few test with all other controllers and then ask also @tammeryousef1006 if he can try with his ones.

I will let you know.

**Comment by aryelevin** [comment]
Perfect.
Thank you.
Have a great weekend :)

**Comment by Luligu** [comment]
Voila, like I thought in Home Assistant shows up:

![image](https://github.com/user-attachments/assets/a84a03de-9926-42da-b772-47fe9901b01b)

**Comment by Luligu** [comment]
You can see the code (almost nothing btw) in the dev branch of matterbridge-example-dynamic-platform.

**Comment by aryelevin** [comment]
OK, seems cool.
Have you tried your code on Apple Home? (Just to verify its isn't supported)

Thanks again

**Comment by aryelevin** [comment]
OK, I updated some code to match your code, now Apple Home shows a "Not Supported" accessory.
Now we know it simply not supported.
Thanks once again

**Comment by Luligu** [comment]
It will take a while to have all matter device types and clusters in all controllers…
The today’s situation is already much better then 6 months ago 
I expect a big new release of Home app supporting the new device types.
