### ISSUE TITLE
manufacturer, serial number and model = unkown after first restart

### ISSUE THREAD

**Issue by pasqualito79** [Luligu/matterbridge#191]
Hi there,

when I configure a new device (in my case different shelly models) they are exposed with the correct manufacturer, serial number and model in Apple home. After a restart time, the three values are set to "unknown" and will always stay like this.

**Comment by Luligu** [comment]
Hi,
I'm aware of it. 
My main controller is Home too.
Nothing I can do about that unfortunately.  It is a Home issue. If you have other HomeKit apps like Eve or Controller you see them correctly.
All other controllers don't have that issue.
