### ISSUE TITLE
throw new StorageError("The storage needs to be initialized first!");

### ISSUE THREAD

**Issue by kskenyon** [Luligu/matterbridge#22]
I get this error now with :dev.  What do I have to do?

matterbridge    | [23:29:22.680] [Matterbridge] Matterbridge version 1.2.13 mode bridge restart mode docker running on Linux 6.1.28-v8+ linux arm 
matterbridge    | [23:29:22.694] [Matterbridge] Storage initialize() error! 
matterbridge    | [23:29:22.697] [Matterbridge] Storage initialize() error! 
matterbridge    | file:///app/node_modules/@project-chip/matter.js/dist/esm/storage/StorageManager.js:28
matterbridge    |       throw new StorageError("The storage needs to be initialized first!");
matterbridge    |             ^
matterbridge    | 
matterbridge    | StorageError: The storage needs to be initialized first!
matterbridge    |     at StorageManager.createContext (file:///app/node_modules/@project-chip/matter.js/dist/esm/storage/StorageManager.js:28:13)
matterbridge    |     at Matterbridge.createCommissioningServerContext (file:///app/dist/matterbridge.js:1763:52)
matterbridge    |     at Matterbridge.parseCommandLine (file:///app/dist/matterbridge.js:377:47)
matterbridge    | 
matterbridge    | Node.js v20.12.2

pi@pi3:~/.matterbridge $ ll
total 32
-rw-r--r-- 1 root root 8077 May  3 16:57 matterbridge.backup.json
-rw-r--r-- 1 root root   68 Apr 28 13:19 matterbridge-eve-door.config.json
-rw-r--r-- 1 root root   70 Apr 28 13:19 matterbridge-eve-energy.config.json
-rw-r--r-- 1 root root   70 Apr 28 13:19 matterbridge-eve-motion.config.json
-rw-r--r-- 1 root root   68 Apr 28 13:19 matterbridge-eve-room.config.json
-rw-r--r-- 1 root root   71 Apr 28 13:19 matterbridge-eve-weather.config.json
-rw-r--r-- 1 root root    0 May  3 23:05 matterbridge.json
drwxr-xr-x 8 root root 4096 Apr 28 11:30 storage

pi@pi3:~/matterbridge $ ll
total 4
-rw-r--r-- 1 pi pi 466 Apr 28 11:02 docker-compose.yml

services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:dev # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - "${HOME}/matterbridge:/root/matterbridge" # Mounts the Matterbridge plugin directory
      - "${HOME}/.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory

**Comment by Luligu** [comment]
Hi,
when you get this error means that the Matter storage (all pairing information) get corrupted.
Stop the container.
Delete matterbridge.json (If matterbridge.backup.json is still correct, rename it matterbridge.json).
Restart the container.

**Comment by kskenyon** [comment]
Thanks, that worked.
