### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by donavanbecker** [Luligu/matterbridge#29]
Will macOS be added at some point? so that it can be installed as a service.

**Comment by Luligu** [comment]
Hi,
sorry for the late answer.
I have no knowledge of macOS.
Can you explain me if you encounter problem please?

**Comment by donavanbecker** [comment]
Well for one thing it would be nice if a `Launchctl Service File` could be generated that would start matterbridge. Similar to how you have a systemctl for linux here: https://github.com/Luligu/matterbridge/blob/main/README.md#run-matterbridge-as-a-daemon-with-systemctl-linux-only

I was receiving an error but tried installing again and not getting that right now

**Comment by donavanbecker** [comment]
```
eneralDiagnosticsCluster.setNetworkInterfacesAttribute for Matterbridge error: ValidationError: Validation error for attribute "networkInterfaces"in field [0].iPv6Addresses.[0]: (Validation/135) String is too short: 12, min 16.
2024-05-24 10:43:41     at StringSchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvString.js:39:13)
2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:62:34)
2024-05-24 10:43:41     at tryCatch (file:///app/node_modules/@project-chip/matter.js/dist/esm/common/TryCatchHandler.js:8:12)
2024-05-24 10:43:41     at file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:61:7
2024-05-24 10:43:41     at Array.forEach (<anonymous>)
2024-05-24 10:43:41     at ArraySchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:60:10)
2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvObject.js:137:24)
2024-05-24 10:43:41     at tryCatch (file:///app/node_modules/@project-chip/matter.js/dist/esm/common/TryCatchHandler.js:8:12)
2024-05-24 10:43:41     at ObjectSchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvObject.js:136:9)
2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:62:34) {
2024-05-24 10:43:41   code: 135,
2024-05-24 10:43:41   clusterCode: undefined,
2024-05-24 10:43:41   fieldName: '[0].iPv6Addresses.[0]'
2024-05-24 10:43:41 } 
```

**Comment by Apollon77** [comment]
Hm ... I also use macos and I never got that error. I will enhance the exception to also contain the invalid value and not only the details about the error, then we might be able to see a reason.

It might help to show your network interfaces. ideally do on a command line

`node` and then enter `os.networkInterfaces()`  ... please post the result

**Comment by Luligu** [comment]
Thanks Apollon

> Hm ... I also use macos and I never got that error. I will enhance the exception to also contain the invalid value and not only the details about the error, then we might be able to see a reason.
> 
> It might help to show your network interfaces. ideally do on a command line
> 
> `node` and then enter `os.networkInterfaces()` ... please post the result

**Comment by Luligu** [comment]
> ```
> eneralDiagnosticsCluster.setNetworkInterfacesAttribute for Matterbridge error: ValidationError: Validation error for attribute "networkInterfaces"in field [0].iPv6Addresses.[0]: (Validation/135) String is too short: 12, min 16.
> 2024-05-24 10:43:41     at StringSchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvString.js:39:13)
> 2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:62:34)
> 2024-05-24 10:43:41     at tryCatch (file:///app/node_modules/@project-chip/matter.js/dist/esm/common/TryCatchHandler.js:8:12)
> 2024-05-24 10:43:41     at file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:61:7
> 2024-05-24 10:43:41     at Array.forEach (<anonymous>)
> 2024-05-24 10:43:41     at ArraySchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:60:10)
> 2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvObject.js:137:24)
> 2024-05-24 10:43:41     at tryCatch (file:///app/node_modules/@project-chip/matter.js/dist/esm/common/TryCatchHandler.js:8:12)
> 2024-05-24 10:43:41     at ObjectSchema.validate (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvObject.js:136:9)
> 2024-05-24 10:43:41     at error.fieldName (file:///app/node_modules/@project-chip/matter.js/dist/esm/tlv/TlvArray.js:62:34) {
> 2024-05-24 10:43:41   code: 135,
> 2024-05-24 10:43:41   clusterCode: undefined,
> 2024-05-24 10:43:41   fieldName: '[0].iPv6Addresses.[0]'
> 2024-05-24 10:43:41 } 
> ```

Just to be sure what version of Matterbridge are you using ?

**Comment by donavanbecker** [comment]
sorry have been busy. Th latest version seems to resolve this and I am not seeing this error. 

However I am not seeing the bridge in the Home App.

**Comment by donavanbecker** [comment]
@Luligu would you know his to create a startup script for macOS? If a user closes terminal the matterbridge dies

**Comment by Apollon77** [comment]
maybe that could be an ideal topic to deliver by the community? ;-))
But yes, maybe looking at how homebridge or iobroker does it could help? (iobroker like https://github.com/ioBroker/ioBroker/blob/master/installer.sh#L429-L465)
