### ISSUE TITLE
MatterBridge didn't reconnect to home Assistant matter server after restart

### ISSUE THREAD

**Issue by L2jLiga** [Luligu/matterbridge#32]
Hello, I actually don't really know if this issue should goes here or I have to create it in python matter server repository.

Given:
Home Assistant 2024.5
Python matter server 6.0.1
Yeelight matter hub
Moes matter hub
MatterBridge  1.2.17
MatterBridge zigbee2mqtt plugin 2.0.14

When I power-off / power-on yeelight or moes matter hubs then they reconnect to HA matter server without any problem

When I restart MatterBridge, then MatterBridge and provided devices becomes unavailable until I manually restart HA Matter Server.

After HA Matter Server restart devices are back and works fine until MatterBridge restart, I've tested they are worked without any issues for at least a weak

**Comment by Luligu** [comment]
Hi thank you for your message.

HA is my controller for test so I use it a lot.

As I wrote in the help page for the plugin:
Home Assistant issues (Matter Server for HA is still in Beta)
If HA doesn't show all devices just reload the HA Matter Server

Considering it is a beta is acceptable I guess.

Btw I didn't notice that issue since after the last Matter server / core update.
Check if you have to update it maybe.

**Comment by Luligu** [comment]
Just one more thing.

If you look at the log you can see when the controller connects again.
That is a starting point to understand the issue.

**Comment by tammeryousef1006** [comment]
> Hello, I actually don't really know if this issue should goes here or I have to create it in python matter server repository.
> 
> Given: Home Assistant 2024.5 Python matter server 6.0.1 Yeelight matter hub Moes matter hub MatterBridge 1.2.17 MatterBridge zigbee2mqtt plugin 2.0.14
> 
> When I power-off / power-on yeelight or moes matter hubs then they reconnect to HA matter server without any problem
> 
> When I restart MatterBridge, then MatterBridge and provided devices becomes unavailable until I manually restart HA Matter Server.
> 
> After HA Matter Server restart devices are back and works fine until MatterBridge restart, I've tested they are worked without any issues for at least a weak

kindly update to latest matterbridge and give your feedback if you face any issue

**Comment by L2jLiga** [comment]
Hello, sorry for long delay, was busy with testing different setups (on bare metal, in kubernetes, in HA as addon) 😅

Btw, as of now it seems to be stable enough with latest versions of HA, Matter server and MatterBridge 

btw if you're interested, I've wrapped MatterBridge in HomeAssistant addon with zigbee2mqtt onboard
https://github.com/L2jLiga/ha-addons
https://github.com/L2jLiga/ha-addons-built

**Comment by Luligu** [comment]
Hi,
I'm very interested.
Can we move this to a discussion?
So it remains open and available for everyone and you can update the info?

**Comment by L2jLiga** [comment]
> Hi, I'm very interested. Can we move this to a discussion? So it remains open and available for everyone and you can update the info?
> 
> #49

Sure
