### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by t0bst4r** [Luligu/matterbridge#36]
Hey @Luligu,

I just wanted to let you know, that I am currently working on a [Home Assistant Integration](https://github.com/t0bst4r/matterbridge-home-assistant), which was requested in the [home assistant community](https://community.home-assistant.io/t/act-as-a-matter-bridge/519019/23).

It currently supports the following devices:

- Light entities (`light.`) including on-off, brightness and hue & saturation control
- Switch entities (`switch.`) including on-off control
- Media Players (`media_player.`) are mapped to Switches and currently only support on-off control

Next step will be to build a docker image (or add my plugin to yours?) and then wrap it into a ready-to-use HomeAssistant AddOn.

**Comment by Luligu** [comment]
Hi,
very interesting.
Let me know how can I support you and I will with great pleasure.
For the plugin as soon as you are ready we can add it to readme.md.

**Comment by t0bst4r** [comment]
I have created a new docker image for my specific use case and we are currently working on putting it into a ready-to-use HA addon. 
We‘ll still need some iterations on both 😄 

The plugin lib itself seems to work quite well. 👍🏼
