### ISSUE TITLE
matterbridge.json save errors

### ISSUE THREAD

**Issue by kskenyon** [Luligu/matterbridge#42]
matterbridge.json is often saved as a zero length file necessitating replacing it with matterbridge.backup.json.

I don't know the reason this happens but can it be fixed so it does not happen?  Might be related to installing updates?

Kevin

**Comment by Luligu** [comment]
Hi,
thank you for your message.
This is the first time I hear this issue.
So is probably related to your installation.
Can you tell me more about that?
How do you run Matterbridge? 
Os?
Bridge mode or Childbridge mode?
Docker or service or standalone?
And when this happens?

**Comment by Luligu** [comment]
So, it seems a standard configuration but I would not run docker compose without -d.
Btw the file 0 length means that it crashed while matter was writing to it. Maybe memory or hardware problems on the raspberry. When it happens try to look at the log before to see if something happened before... this can help you to identify the problem.

**Comment by Luligu** [comment]
Hi, any news?
Can I close the issue ?

**Comment by kskenyon** [comment]
Seems OK if I don't use docker-compose up then kill it.  Close it.

**Comment by Luligu** [comment]
Then probably is a sort of docker weakness.
Good to know that everything is working fine.
