### ISSUE TITLE
Installation error npm ERR! Cannot set properties of null (setting 'dev')

### ISSUE THREAD

**Issue by khaidakin** [Luligu/matterbridge#5]
When trying to install matterbridge on raspbian I get: npm ERR! Cannot set properties of null (setting 'dev')

Here are the details from the log file:

471 timing build:link:node_modules/matterbridge Completed in 20ms
472 timing build:link Completed in 22ms
473 timing build:deps Completed in 65ms
474 timing build:queue Completed in 1ms
475 timing build:links Completed in 1ms
476 timing build Completed in 72ms
477 timing reify:build Completed in 77ms
478 timing reify:trash Completed in 1184ms
479 timing command:install Completed in 41885ms
480 verbose stack TypeError: Cannot set properties of null (setting 'dev')
480 verbose stack     at calcDepFlagsStep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:34:21)
480 verbose stack     at visit (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:12:20)
480 verbose stack     at visitNode (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
480 verbose stack     at next (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
480 verbose stack     at depth (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
480 verbose stack     at depth (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)
480 verbose stack     at calcDepFlags (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/calc-dep-flags.js:10:15)
480 verbose stack     at [copyIdealToActual] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:1551:7)
480 verbose stack     at Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:172:35)
480 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:153:5)
481 verbose cwd /home/pi
482 verbose Linux 5.10.103-v7+
483 verbose node v18.17.1
484 verbose npm  v10.5.0
485 error Cannot set properties of null (setting 'dev')
486 verbose exit 1

**Comment by Luligu** [comment]
Hi,
thank you for your message.
You are right it's my fault.
The 1.1.7 is online on npm with the fix (I forgot to remove debug dependencies).
Just let me know but it install on all my machines.
Have a nice day.

**Comment by Luligu** [comment]
Thank you. 
I appreciate your message.
When you have a plugin tell me that I will link it to the home page.
This release is now fully async.

**Comment by Luligu** [comment]
Can you reach me on Discord ?

**Comment by khaidakin** [comment]
I sent you a message
