### ISSUE TITLE
Set log level of AnsiLogger to "INFO" when "-debug" is not set

### ISSUE THREAD

**Issue by t0bst4r** [Luligu/matterbridge#50]
At the moment the "-debug" flag seems to have the following effects:
- set the `defaultLogLevel` for the `Logger` from matter.js ([example here](https://github.com/Luligu/matterbridge/blob/main/src/matterbridge.ts#L289))
- set `logDebug` for the `AnsiLogger` ([example here](https://github.com/Luligu/matterbridge/blob/main/src/matterbridge.ts#L390))

Anyway every log written to `this.log.debug` gets printed, even when `-debug` is not set.

It would be nice if:
1. the absence of the debug flag configures ansi logger to NOT print debug logs
2. OR EVEN BETTER a general `-log [debug|info|warn|error]` option could be added which configures BOTH loggers properly

Thank you!

**Comment by Luligu** [comment]
Hi,
could you please post to the discussion I created for your project so we have all the stuff in the same place?

1) Anyway every log written to this.log.debug gets printed, even when -debug is not set.
Can you show me with a screenshot what do you mean? Cause is not clear for me where you see a debug printed when -debug is not enabled.

2) In the first link provided you are inside startExtension: that is an undocumented and no more maintained method that I left there in case I decide to continue that project (z2m extension). It is not supposed to be used. If you use it in your code please tell me that I have to verify that the code there is still up to date with Matterbridge. 

3) OR EVEN BETTER a general -log [debug|info|warn|error] option could be added which configures BOTH loggers properly
Is a good idea I will do it. Actually that is already managed that way in the frontend but the command line has been left behind...
<img width="499" alt="image" src="https://github.com/Luligu/matterbridge/assets/132135057/44663d3b-31c2-4d80-987b-33866bf8b942">

**Comment by t0bst4r** [comment]
I thought, if its really a bug, it's rather an issue than a discussion - if not, feel free to close the issue, and i'll post it to the discussion again.

---

I think I found the one, printing debug logs, which i was re-using by extending the `MatterbridgeDevice` and using `this.log`:

https://github.com/Luligu/matterbridge/blob/main/src/matterbridgeDevice.ts#L203

**Comment by Luligu** [comment]
Hi,
yes indeed, it's a kind of bug. 
I was refactoring the console.log to AnsiLogger and it remained there unfinished.
In the dev is correct.
I will publish before evening:

Also this is done:
https://github.com/Luligu/matterbridge/issues/51

## [1.3.0] - 2024-06-16

This release is all about Matter 1.3

If you are wondering whether the controllers already support Matter 1.3, the answer is unfortunately no.

Only Home Automation supports:
- airQualitySensor (Matter 1.2)

and (probably only like BooleanState cluster)
- waterFreezeDetector (Matter 1.3)
- waterLeakDetector (Matter 1.3)
- rainSensor (Matter 1.3)

### Changed
- [matterbridge]: Updated dependencies
- [matterbridge]: Default config and schema for the new plugin matterbridge-shelly (will be published after this release)

### Added
- [matterbridgeDevice]: Added waterFreezeDetector, waterLeakDetector, rainSensor, smokeCoAlarm, electricalSensor and deviceEnergyManagement device types as conformance to Matter 1.3
- [matterbridgeDevice]: Added all clusters needed for the above Matter 1.3 device types 
- [matterbridgeDevice]: Added FanControl cluster (rev. 2) helper methods for the Fan device type

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

Tell me about the startAsExtension... please.
