### ISSUE TITLE
Fan support

### ISSUE THREAD

**Issue by genehand** [Luligu/matterbridge#51]
Hey we're stirring up interest with the addition of the home assistant plugin and it's working well for people so far.  I was asking about potential [support for fans](https://github.com/t0bst4r/matterbridge-home-assistant/issues/70) and realized that may need to be added here first.  Is that the case or could it be implemented directly in a plugin?

Thanks again!

**Comment by Luligu** [comment]
Hi,
the FanControl cluster is already in the dev with some new Matter 1.3 devices and relative clusters:

  name: 'MA-waterFreezeDetector',
  code: 0x0041,

  name: 'MA-waterLeakDetector',
  code: 0x0043,

  name: 'MA-rainSensor',
  code: 0x0044,

  name: 'MA-smokeCoAlarm',
  code: 0x0076,

  name: 'MA-electricalSensor',
  code: 0x0510,

  name: 'MA-deviceEnergyManagement',
  code: 0x050d,

I will publish it as soon as possible (before Monday). Still need some more check on it and a controller that supports the new device types...

**Comment by genehand** [comment]
> I will publish it as soon as possible (before Monday). Still need some more check on it and a controller that supports the new device types...

Ah great timing, thanks

**Comment by Luligu** [comment]
Hi,
as promised will be published today.

![Fan](https://github.com/Luligu/matterbridge/assets/132135057/d6999dcd-a0f2-44bd-9e50-83cb94a8ab27)

And a lot of other stuff.

Let me know if I can be of help for your project.
