### ISSUE TITLE
[Feature Request] Home Assistant add-on

### ISSUE THREAD

**Issue by Aaroneisele55** [Luligu/matterbridge#53]
Hello,
I would like to know if it would be possible to implement MatterBridge as a Home Assistant add-on...
I have a Raspberry Pi 4 running HAOS,  and I would like to also run matterbridge alongside HA, which would be possible by using an add-on.

Best regards 
Aaron Eisele

**Comment by Luligu** [comment]
Hi,
there are some projects of HA add-on.
Look in the discussions if they are what you are looking for.
You can probably run Matterbridge like a service or docker on the same machine too I guess.
Best regards.

**Comment by Caligo82** [comment]
[https://smarthomescene.com/guides/exposing-home-assistant-entities-as-matter-devices/](url)

**Comment by dahLucky** [comment]
@Aaroneisele55 Direct link to the add-on repo is: https://github.com/t0bst4r/matterbridge-home-assistant-addon
