### ISSUE TITLE
Bug: Cannot connect to Google Home on IOS

### ISSUE THREAD

**Issue by Ultra-bob** [Luligu/matterbridge#61]
Originally posted on the home assistant plugin repo, but it's a problem even with no plugins so posting it here
https://github.com/t0bst4r/matterbridge-home-assistant/issues/93
I've set up matterbridge and all my HA devices show up, but when trying to add it to Google Home with my iPhone, it fails.
Debug logs attached (they didn't fit)
[matterbridge-logs.txt](https://github.com/user-attachments/files/15946413/matterbridge-logs.txt)

**Comment by Ultra-bob** [comment]
How do I disable a network interface? These were all enabled by default.

**Comment by Luligu** [comment]
Hi,
concerning the pairing issue Apollon is the best expert to answer you.

Concerning Matterbridge:
[23:18:54.601] [Matterbridge] Matterbridge is out of date. Current version: 1.2.22, Latest version: 1.3.0 
Why you are using a so old version ?

**Comment by Luligu** [comment]
> How do I disable a network interface? These were all enabled by default.

What machine are you running matterbridge on ?

**Comment by Ultra-bob** [comment]
> What machine are you running matterbridge on ?
It's running on my home server (old gaming pc) through docker

> Why you are using a so old version ?
These are old logs, I'm on the latest version and same issue

**Comment by Ultra-bob** [comment]
> Please reboot hub and also mobile devcie and make sure that the "current" firmwares are on it and not updates outstanding.

I rebooted the hub, my phone, checked that the hub has latest firmware and checked for updates on google home app. Still same issue

**Comment by EffortlessHome** [comment]
I have the same issues as @Ultra-bob. Pairing doesn't work with IOS and Google Home on latest everything. Love the project and watching this thread closely. Let me know if you want my logs too.

**Comment by Luligu** [comment]
Hi,
the log would be usefull for sure.
Apple Home is my primary controller and I can assure you that it has never ever failed to pair Matterbridge/matter.js device once.
So it can can be something specific to your setup.
Maybe with the log we will understand.

**Comment by Apollon77** [comment]
Yes Debug log please ... and make sure that your docket is correctly configured and UDP messages can flow all between the network of the Apple/Google mobile app,s pods and the matterbridge host ... no VLANs in place that could block UDP routing ...

But in fact log should show whats up ... because if you see nothing happening ion the log at all then UDP is blocked somewhere. If you see incoming traffic then we can look deeper with the log

**Comment by EffortlessHome** [comment]
Appreciate the help. I have tried to pair again with IOS and Google Home. Debug logs attached. My environment is Home Assistant running on an HA Green with the Matterbridge Addon. I don't have a HomeKit device, just several different models of Google/Nest speakers/hubs. 
[debug.txt](https://github.com/user-attachments/files/15988302/debug.txt)

**Comment by Apollon77** [comment]
I need a bit more context for this way to short log :-)

It seems that something is connected and was reading data from 192.168.1.231 ... whats that?

Other then that I do not see any incoming traffic. (if I assume that you tried it in the shown log timeframe). What error is iOS/Google showing you? if it can not find any accessory/device then check your UDP traffic routing. The mobile apps and also the hubs need to be able to communicate with UDP with the matterbridge. So in fact "see above" ... it seems somethings blocks the UDP traffic and you also need IPv6 enabled

**Comment by Ultra-bob** [comment]
> Appreciate the help. I have tried to pair again with IOS and Google Home. Debug logs attached. My environment is Home Assistant running on an HA Green with the Matterbridge Addon. I don't have a HomeKit device, just several different models of Google/Nest speakers/hubs. [debug.txt](https://github.com/user-attachments/files/15988302/debug.txt)

When I try to pair it a second time without resetting, nothing shows in logs and there is a connection failed error, whereas on the first try there is a setup failed error and there are lots of logs. Try resetting the commissioning in the settings

**Comment by Ultra-bob** [comment]
Here are my updated logs and error messages
![image](https://github.com/Luligu/matterbridge/assets/6679
[logs.txt](https://github.com/user-attachments/files/15988831/logs.txt)
1664/9bc41c60-8f8a-46cf-8878-6567107b3517)

**Comment by Apollon77** [comment]
@Ultra-bob Ok the log shows the following:
* fe80::1876:1879:4fa4:c87%eno1 connects and commissions correctly one fabric ... that should be the mobile device you use with Apple Home app
* then it opens the second commissioning window as normal for apple
* then the second commissioning process runs till csrRequest and then the app sends this command 3 times and then stops.
Reason ... unknown ... in fact the response to the request was received by  the apple device

For now I can only ask to check and make sure all stuff is properly updated and please provide app and ios versions. Also I only tests with the "Apple home" being migrated to this new architecture ... no idea if there are issues with the old.
Do you maybe have a second apple mobile device to try it too?

**Comment by Apollon77** [comment]
Ok @EffortlessHome you have the same as @Ultra-bob and now I have an idea ...

You do Google on ios ... got it ...  DId you added the device to your google developer console? see https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#google-home-ecosystem ... Please try this!
Long time this was only needed for Android ... and iOs pairing worked without it ... But the place where it fails would be reasonable for the case that they decline the "not certified status".

**Comment by Ultra-bob** [comment]
I'm trying to set that up, but I don't know what to add for the product id and whatever else
![image](https://github.com/Luligu/matterbridge/assets/66791664/db6434bb-af16-464c-beac-773fae370765)

**Comment by Ultra-bob** [comment]
IT WORKED!

I looked more carefully at the settings and saw every device has product id 0x800 and set that, and then everything worked perfectly. Thanks so much for all your help @Apollon77 and @Luligu

**Comment by Apollon77** [comment]
For clarity: it is 0x8000 not 0x800 :-))

**Comment by EffortlessHome** [comment]
Thanks @Apollon77, with that value it also works for me. Can you shed any light on why that is the magic value and if this can be patched in Matterbridge to avoid this in the future?

**Comment by Apollon77** [comment]
Matter has a bid trust basis based on crypto certificates and such. Each device which was officially certified is getting an onw certificate for the Vendor (and the vendor gets a vendor Id) and then has certified devices (productIds). And everything is officially "pinned" with the certification.
There are special VendorIds and productids reserved for "devices in development and testing" and because matterbridge is no certified product is uses these test device IDs.

Formally the certificates used here are self signed and so not 100% as secure as the official devices and also not certified and so could behave wrong according to the standard. In fact each ecosysterm/Controller can not decide how to work with such test devices. Some just warn/inform and some (we had that for Aqara) block them ... Google chose a middle way with this "whitelisting in developer console".

This is in the end inconvenient for test devices.

The reality is that most likely matterbridge and other open source implementation s(also e.g. matter,js example scripts, tasmota integration) will never be certified officially and so this topic will stay. The reason is not that noone wants it to do certification, but in fact all this requires
* being a CSA Member (costs money)
* paying a service provider to do the certification initially ... and also when adding new features updating that!
* paying a Certification Authority to generate device certificates per device (aka installation)
Nothing of this will be possible for open source non-commercial projects (and also spending some coffees or spending funds will not really help here on the long run.

**Comment by EffortlessHome** [comment]
Makes sense, thanks for the detailed explanation and your assistance. Great work on this project, keep it up!

**Comment by Ultra-bob** [comment]
Maybe there should be a note added to the docs so no-one else has to deal with this, but I think it's resolved now.

**Comment by Luligu** [comment]
Hi,
thank you so much.
I added a note to the readme.

**Comment by rexhoffman** [comment]
Been trying to follow the setup steps and seeing the same error.   0xfff1, 0x8000 and still no love.   Left the google config in a Test mode, and logged in to the test console - getting security warnings.   Don't you suppose you could write up your steps more clearly @Ultra-bob?

**Comment by Ultra-bob** [comment]
1. I went to https://console.home.google.com/projects and used my existing project for controlling my nest thermostat (not sure what I did to create that project in GCP)
2. Created a new matter device in the Develop section with the settings in my above screenshot (except product id set to 0x8000)

Not sure what you mean by test console and test mode, I stopped after the develop part and saved the branding

The difference is probably with how I initially created the google cloud project when setting up my Nest thermostat, so maybe following that guide https://www.home-assistant.io/integrations/nest/#configuration will help?

**Comment by rexhoffman** [comment]
I found that I needed to "Reset Matterbridge Commissioning", to remove HomeKit integration, and then add the bridge to google home first.    I could not reconnect to apple HomeKit afterwards.

**Comment by Apollon77** [comment]
> I found that I needed to "Reset Matterbridge Commissioning", to remove HomeKit integration, and then add the bridge to google home first. I could not reconnect to apple HomeKit afterwards.

What do you mean? As soon as you have paired it to one controller you need to use this controller to get a second pairing code to add another ecosystem! You can not use teh same qr code again!

**Comment by Luligu** [comment]
Hi,
that's correct. 
In one of the next release I will change the QR code in the frontend with the FabricInfo when the bridge/plugin is already paired and connected.
Now is actually not clear that you can use the QR only once.

**Comment by Luligu** [comment]
> > Please reboot hub and also mobile devcie and make sure that the "current" firmwares are on it and not updates outstanding.
> 
> I rebooted the hub, my phone, checked that the hub has latest firmware and checked for updates on google home app. Still same issue

Hi,
in the latest there is a command line parameter to limit the interfaces used for Matter advertise. 
You can try to use it to limit to the main interface.

**Comment by Ultra-bob** [comment]
> > > Please reboot hub and also mobile devcie and make sure that the "current" firmwares are on it and not updates outstanding.
> > 
> > 
> > I rebooted the hub, my phone, checked that the hub has latest firmware and checked for updates on google home app. Still same issue
> 
> Hi, in the latest there is a command line parameter to limit the interfaces used for Matter advertise. You can try to use it to limit to the main interface.

How would I do that for the docker version?
