### ISSUE TITLE
Accessory Not Found

### ISSUE THREAD

**Issue by sandeepb1** [Luligu/matterbridge#64]
I've installed the latest version of matterbridge with the latest version of npm and it starts perfectly fine.

No addons have been installed yet but when I try to add the bridge to HomeKit I'm presented with an "Accessory not found" error - I've tried the following

- Reset my router
- Reboot my phone
- Reboot my HomePod Mini
- Reset Matterbridge Commissioning
- Changed to a WiFi Network that uses only 2.4Ghz
- Removed all firewall rules to ensure nothing is blocked

Using the following devices

- iPhone 15 Pro Max
- Apple HomePod Mini

**Comment by Apollon77** [comment]
A Bridge without any devices it is most likely not possible to be commissioned and could already be the reason for this error ... So please add at least a device into the bridge and try again.

**Comment by sandeepb1** [comment]
I've also tried with the matterbridge-home-assistant-addon in Home Assistant where it has populated all my devices and still receive the "Accessory not found"

**Comment by Apollon77** [comment]
Then please enable debug logging and try again

If you do not see any traffic incoming then check that UDP is routed everywhere without issues - especially with docker and such. all routes need to allow UDP traffic flowing!

If you see traffic incoming we can look whats up

**Comment by sandeepb1** [comment]
Found the issue, VLANs 😞

**Comment by Apollon77** [comment]
I hope you find ways to configure the router to route UDP

**Comment by Luligu** [comment]
Is always related to mdns issues in my experience.
If the network is working, Matterbridge/matter.js devices never ever fails to pair with Apple Home.
Is the most stable controller since version 17.5 also with the HomePod that is a WiFi device..
Glad you solved.
