### ISSUE TITLE
Homebridge + Matterbridge

### ISSUE THREAD

**Issue by donavanbecker** [Luligu/matterbridge#67]
Have you had any thought of merging them together? Implementing all of the matter functionality into Homebridge so a developer could update their plugin to use either or?

**Comment by Luligu** [comment]
Hi,
actually at the beginning of this adventure my idea was to be able to load the homebridge plugins in matterbridge but the mapping from the twos is simply to difficult.
I ported my existing plugins to matterbridge without having to recode all...

**Comment by donavanbecker** [comment]
Thanks. If you would like to merge the two let us know.

**Comment by Luligu** [comment]
What do you mean exactly ?

**Comment by NebzHB** [comment]
@donavanbecker a homebridge plugin like homebridge-gsh or homebridge-alexa that connect to matterbridge to translate equipments from homebridge to matterbridge might be interesting :)

**Comment by NebzHB** [comment]
Dear, would you re-open that issue ?

**Comment by sierralx** [comment]
I've tested the new Matter-hub, and I believe I will miss Matterbridge due to its user-friendly interface and simplicity for including domains, patterns, labels, exclusions, etc. I hope that the two projects can be merged for a more streamlined experience. 🤝
