### ISSUE TITLE
Shutter opening/closing state in Apple Home

### ISSUE THREAD

**Issue by nitaybz** [Luligu/matterbridge#69]
Hi,

I'm not sure wether it's a Matter issue, or maybe Apple/matterbridge/zigbee2mqtt, but I'm experiencing an issue where the Shutters are always showing "opening..." or "closing...". it seems like the status is reported correctly in z2m and also in Home Assistant integrated with matterbridge, I even tried to export the 2 shutters I have from homeassistant (via matterbridge) back to HomeKit and than I get the status reported correctly with the opening/closing state stuck.

do you think it's something you could look into?
do you need anything from me?

**Comment by Luligu** [comment]
Hi,
Apple is my first controller, and I have rollers on it from all plugins [matterbridge-zigbee2mqtt](https://github.com/Luligu/matterbridge-zigbee2mqtt), [matterbridge-somfy-tahoma](https://github.com/Luligu/matterbridge-somfy-tahoma) and [matterbridge-shelly](https://github.com/Luligu/matterbridge-shelly).
So generally speaking there are no problems.

The WindowCovering cluster in matter requires an initial configuration that is done by all plugins when the first controller connects to the bridge.

You should see in the log 
[16:28:01.672] [Matterbridge zigbee2mqtt plugin] Configuring xxx matter devices.

After this has been done, in the Devices section of the frontend find your device in the first table and select it, the in the second table find the WindowCovering cluster and send me please the screenshot of the operationalStatus, targetPositionLiftPercent100ths and currentPositionLiftPercent100ths attributes.

Also what zigbee device you use for roller?

Can you also explain me how you are using matterbridge in your setup, cause I didn't get it.

**Comment by nitaybz** [comment]
Hey, thanks for the fast reply, I'm including some screenshots from my iPhone that will answer all your questions including what device I'm using, the state in z2m and how it looks in Apple Home. Let me know if anything else is needed.

![image](https://github.com/Luligu/matterbridge/assets/16838394/dc7e99c2-ba96-4b0e-a5a1-f916ab633c3b)
![image](https://github.com/Luligu/matterbridge/assets/16838394/4bab484b-9e04-4b8f-9f42-90fd88aac268)
![image](https://github.com/Luligu/matterbridge/assets/16838394/b12ea174-7544-465a-bdc8-917f03895213)
![image](https://github.com/Luligu/matterbridge/assets/16838394/39559fbc-c641-49e5-aaf7-5d931324a6c8)
![image](https://github.com/Luligu/matterbridge/assets/16838394/759a2589-7664-4d62-8469-a2947e24a89e)

Regarding my plugins, I'm planning to move some of them, I just hope to find some time for it.

Thanks in advance :)

**Comment by Luligu** [comment]
Hi,
ok the problem is that targetPositionLiftPercent100ths and currentPositionLiftPercent100ths don't match as you saw.

Did you see the message [16:28:01.672] [Matterbridge zigbee2mqtt plugin] Configuring xxx matter devices.

The problem persist even when you full close or full open the cover? Or is just when the controller starts? Cause I will look in different parts of the code.

I don't know that zigbee device: can you send me the bridge-devices.json file in the Matterbridge\matterbridge-zigbee2mqtt dir please.

**Comment by nitaybz** [comment]
The problem persist even when it's half way and when fully close or fully open. I've noticed it happens when you control the device from the switch physically and not from the app.

**Comment by nitaybz** [comment]
bridge-devices.json:
[bridge-devices.json](https://github.com/user-attachments/files/16049962/bridge-devices.json)

it is controllable by Apple Home, and I only see the issue there, but it is also connected to Home Assistant and Google Home.

**Comment by nitaybz** [comment]
Here is the logs for closing, opening and stopping in the middle while controlling it manually from the switch itself:

```
info - [11:19:48.784] [Matterbridge]: WebSocketServer client connected to Matterbridge
info - [11:20:19.822] [Matterbridge]: Active session changed on fabric 4 id 126025447294428114 vendor 4631 (Alexa) Alexa-4 for Matterbridge { name: 'secure/5371', nodeId: 221273427015071072, peerNodeId: 126025447319362097, fabric: { fabricIndex: 4, fabricId: 126025447294428114, nodeId: 221273427015071072, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: 'Alexa-4' }, isPeerActive: false, secure: true, lastInteractionTimestamp: 1719793121785, lastActiveTimestamp: 1719792938981, numberOfActiveSubscriptions: 0 }
info - [11:20:19.826] [Matterbridge]: Active session changed on fabric 4 id 126025447294428114 vendor 4631 (Alexa) Alexa-4 for Matterbridge { name: 'secure/5410', nodeId: 221273427015071072, peerNodeId: 126025447319362097, fabric: { fabricIndex: 4, fabricId: 126025447294428114, nodeId: 221273427015071072, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: 'Alexa-4' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1719822019885, lastActiveTimestamp: 1719822019885, numberOfActiveSubscriptions: 0 }
info - [11:20:21.936] [Matterbridge]: WebSocketServer client connected to Matterbridge
debug - [11:20:30.882] [Dining Light]: MQTT message for device Dining Light payload: { color_mode: 'xy', led_if_on: 'ON', led_in_dark: 'OFF', linkquality: 220, state: 'OFF', update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
info - [11:20:32.042] [Matterbridge]: Active session changed on fabric 4 id 126025447294428114 vendor 4631 (Alexa) Alexa-4 for Matterbridge { name: 'secure/5371', nodeId: 221273427015071072, peerNodeId: 126025447319362097, fabric: { fabricIndex: 4, fabricId: 126025447294428114, nodeId: 221273427015071072, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: 'Alexa-4' }, isPeerActive: false, secure: true, lastInteractionTimestamp: 1719793121785, lastActiveTimestamp: 1719792938981, numberOfActiveSubscriptions: 0 }
info - [11:20:32.045] [Matterbridge]: Active session changed on fabric 4 id 126025447294428114 vendor 4631 (Alexa) Alexa-4 for Matterbridge { name: 'secure/5410', nodeId: 221273427015071072, peerNodeId: 126025447319362097, fabric: { fabricIndex: 4, fabricId: 126025447294428114, nodeId: 221273427015071072, rootNodeId: 18446744060825763882, rootVendorId: 4631, label: 'Alexa-4' }, isPeerActive: true, secure: true, lastInteractionTimestamp: 1719822032105, lastActiveTimestamp: 1719822032105, numberOfActiveSubscriptions: 1 }
info - [11:20:32.046] [Matterbridge]: Controller 4631 (Alexa) Alexa-4 connected to Matterbridge on session secure/5410
info - [11:20:34.044] [Matterbridge]: Plugin matterbridge-zigbee2mqtt already configured
debug - [11:20:44.263] [Living Room Shutter]: MQTT message for device Living Room Shutter payload: { calibration_mode: 'specific_nllv', color_mode: 'xy', led_if_on: 'OFF', led_in_dark: 'OFF', linkquality: 196, position: 100, state: 'OPEN', tilt: 100, update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
debug - [11:20:44.264] [Living Room Shutter]: Update endpoint 5 attribute WindowCovering-currentPositionLiftPercent100ths from 10000 to 0
debug - [11:20:48.990] [Entrance Wall Light]: MQTT message for device Entrance Wall Light payload: { color_mode: 'xy', led_if_on: 'ON', led_in_dark: 'OFF', linkquality: 96, state: 'OFF', update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
debug - [11:20:55.226] [Living Room Shutter]: MQTT message for device Living Room Shutter payload: { calibration_mode: 'specific_nllv', color_mode: 'xy', led_if_on: 'OFF', led_in_dark: 'OFF', linkquality: 168, position: 44, state: 'OPEN', tilt: 100, update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
debug - [11:20:55.227] [Living Room Shutter]: Update endpoint 5 attribute WindowCovering-currentPositionLiftPercent100ths from 0 to 5600
debug - [11:21:09.274] [Living Room Shutter]: MQTT message for device Living Room Shutter payload: { calibration_mode: 'specific_nllv', color_mode: 'xy', led_if_on: 'OFF', led_in_dark: 'OFF', linkquality: 180, position: 100, state: 'OPEN', tilt: 100, update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
debug - [11:21:09.278] [Living Room Shutter]: Update endpoint 5 attribute WindowCovering-currentPositionLiftPercent100ths from 5600 to 0
debug - [11:21:09.879] [Kitchen Cabinet Light]: MQTT message for device Kitchen Cabinet Light payload: { color_mode: 'xy', led_if_on: 'ON', led_in_dark: 'OFF', linkquality: 192, state: 'OFF', update: { installed_version: 4015615, latest_version: 4015615, state: 'idle' } }
```

**Comment by nitaybz** [comment]
it seems like the issue is fixed now.
when the device stop at a position it reports opening or closing for 1 second and than changes to the correct status. it is no longer stuck in s opening/closing state.

thanks a lot

**Comment by Luligu** [comment]
Great!

It's me to thanks you.
