### ISSUE TITLE
running matter

### ISSUE THREAD

**Issue by tammeryousef1006** [Luligu/matterbridge#8]
hi and many thanks for this great work , is there a way to run matter bridge without seeing the log ? when i run matterbridge -bridge it keep showing the output which is normal i know , but  can i run the command without seeing output so that i can still be able to use the terminal ?

**Comment by Luligu** [comment]
Hi,
actually both on Windows and Linux you can run as many terminal you like.
I suppose you mean that you connect your device (e.g. raspberrypi ?) directly with a screen...
In any case you can run Matterbridge as daemon (systemctl):
# Advanced configuration

## Run matterbridge as a daemon with systemctl (Linux only)

Create a systemctl configuration file for Matterbridge

```
sudo nano /etc/systemd/system/matterbridge.service
```

Add the following to this file, replacing twice USER with your user name (e.g. pi):

```
[Unit]
Description=matterbridge
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/matterbridge -bridge
WorkingDirectory=/home/<USER>/Matterbridge
StandardOutput=inherit
StandardError=inherit
Restart=always
RestartSec=10s
User=<USER>

[Install]
WantedBy=multi-user.target
```

### Start Matterbridge
```
sudo systemctl start matterbridge
```

### Stop Matterbridge
```
sudo systemctl stop matterbridge
```

### Show Matterbridge status
```
systemctl status matterbridge.service
```

### View the log of Matterbridge
```
sudo journalctl -u matterbridge.service -f --output cat
```

### Enable Matterbridge to start automatically on boot

```
sudo systemctl enable matterbridge.service
```

### Disable Matterbridge to start automatically on boot

```
sudo systemctl disable matterbridge.service
```

**Comment by tammeryousef1006** [comment]
Many many thanks bro , the steps above solved my problem and sorry for wrong describe my problem , i should say since beinging i want to run it as service that can auto start upon boot <3
