### ISSUE TITLE
Error installing matterbridge as a daemon

### ISSUE THREAD

**Issue by ionutm80** [Luligu/matterbridge#87]
Hi, I have followed the exact steps to install matterbridge as a daemon in Linux but I get an error, see the screenshot attached. The WEB UI is also not available. If I ssh and run matterbridge -bridge everything works and I can access the GUI but once I hit ctrl-c to stop it in the terminal it becomes unresponsive.
![Error](https://github.com/user-attachments/assets/438c656f-2713-456e-825c-7d5fdef1fbde)

**Comment by Luligu** [comment]
Hi,
if you run Matterbridge like a daemon there is not a ctrlc in the terminal. The process runs like a service. In the terminal you can just connect to the process and see the log using the provided commands.
The gui is available at the address shown on the log.
matterbridge -matter  is not a command. If you run it like a daemon you cannot run it standalone. You have to choose.

**Comment by ionutm80** [comment]
Hi, I ran manually the process and checked its location, it seems that it ran directly from / and not from/usr/bin so I deleted the /usr/bin from ExecStart and now it works perfectly. I now have: ExecStart=matterbridge -bridge -service.
