### ISSUE TITLE
Error on start: empty storage file

### ISSUE THREAD

**Issue by Dischi** [Luligu/matterbridge#88]
Sometimes I cannot start matterbridge. I get the following error:
`CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /home/dirk/.matterbridge/storage/.matterbridge/92cd10e6b8b068a931196d1d73a032543d5ca1a5bf445e27a1af74258254517c does not look like a valid storage file!`

The file is 0 bytes. If I delete the empty file, matterbridge starts but misses its only plugin zigbee2mqtt. 

I do not have any useful debug from the previous session. I start matterbridge with systemd and the colored output is not readable with systemd status.

**Comment by Luligu** [comment]
Hi,
that means that the storage get corrupted.
The storage is not that file but \.matterbridge\storage.
Delete the whole directory. It can happen for hardware issues.

"I do not have any useful debug from the previous session. I start matterbridge with systemd and the colored output is not readable with systemd status." 
The command for reading the log is in the readme: 
sudo journalctl -u matterbridge.service -f --output cat
it reads the log like when you run matterbridge in a terminal.
