### ISSUE TITLE
How to install HomeBridge Plugin?

### ISSUE THREAD

**Issue by cylon147** [Luligu/matterbridge#9]
I am missing information on how to install the existing Homebridge Plugin. As stated in Readme, we can use the existing Homebridge plugin without any code modification. I have tried using the NPMjs plugin path to install the plugin but with no success.
Kindly share More information on this, please

**Comment by NebzHB** [comment]
His question is about the sentence `"This project aims to allow the porting of homebridge plugins to matterbridge plugins without recoding everything."` in the Readme

**Comment by cylon147** [comment]
@NebzHB you are right:)

@Luligu Kindly guide us.

**Comment by Luligu** [comment]
Hi,
sorry for the misunderstanding.
The expression “porting the code,” involves adapting the existing Homebridge plugin code to work seamlessly with Matterbridge.
This process may include modifying APIs, adjusting communication protocols, and ensuring compatibility with Matter’s standards.
It doesn't mean that you can use Homebridge plugins in Matterbridge.
