### ISSUE TITLE
Google Home - Devices Offline

### ISSUE THREAD

**Issue by robvanoostenrijk** [Luligu/matterbridge#92]
After following the setup instructions, I was able to add the MatterBridge Aggregrator in Google Home.

However, even though no errors are displaying in the MatterBridge interface, the devices themselves stay offline in the Google Home app:

![google-home-devices](https://github.com/user-attachments/assets/a3168a7c-d69d-4fd0-8781-67589a79b0fa)

(For now I'm using whitelist to expose only 1 Zigbee device for testing)

MatterBridge WebUI:

<img width="1486" alt="image" src="https://github.com/user-attachments/assets/efabb7c0-ac62-4b20-bfbe-524551996f0c">

I'm not sure how to debug this issue, if its a configuration problem or a bug? Happy to provide more debug logs if required.

**Comment by Luligu** [comment]
Hi,
from your screenshot I see that Google Home has still not connected to Matterbridge: Active sessions: 0

@tammeryousef1006 what do you do when Google Home doesn't connect?

**Comment by robvanoostenrijk** [comment]
Your response led me down the right path. I am running Matterbridge in a FreeBSD Jail on OPNSense.
I did not realize that Matter as a protocol relies on IPv6 LUA connectivity.

For future reference, in a jail the following in /etc/rc.conf made LUA working:

    ifconfig_igc0="inet 192.168.10.6/24"
    defaultrouter="192.168.10.1"

    ifconfig_lo0_ipv6="inet6 ifdisabled"
    ifconfig_igc0_ipv6="inet6 auto_linklocal"
    ipv6_default_interface="igc0"

After these changes Matterbridge is able to communicate with the Google Home hub and a session is established as mentioned. Matterbridge is an awesome piece of work @Luligu!

For those using FreeBSD, rc.d daemon script I am using to run Matterbridge:

    #!/bin/sh

    # PROVIDE: matterbridge
    # REQUIRE: DAEMON NETWORKING mosquitto zigbee2mqtt
    # BEFORE: LOGIN
    # KEYWORD: shutdown

    . /etc/rc.subr

    name=matterbridge
    rcvar=matterbridge_enable
    load_rc_config ${name}

    : ${matterbridge_enable:="NO"}
    : ${matterbridge_log:="/var/log/matterbridge.log"}
    : ${matterbridge_pidfile:="/var/run/matterbridge.pid"}
    : ${matterbridge_node:="/usr/local/bin/node"}
    : ${matterbridge_script:="/usr/local/bin/matterbridge"}
    : ${matterbridge_user:="matterbridge"}
    : ${matterbridge_group:="matterbridge"}

    # daemon
    start_precmd="${name}_prestart"
    command=/usr/sbin/daemon
    procname="daemon"
    pidfile="${matterbridge_pidfile}"
    command_args=" -c -f -P ${matterbridge_pidfile} -o ${matterbridge_log} -R 5 ${matterbridge_node} ${matterbridge_script} -bridge"

    matterbridge_prestart()
    {
        export HOME="/home/${matterbridge_user}"
        install -g "${matterbridge_group}" -m 664 -o "${matterbridge_user}" -- /dev/null "${matterbridge_log}"
        install -g "${matterbridge_group}" -m 664 -o "${matterbridge_user}" -- /dev/null "${matterbridge_pidfile}"
    }

    run_rc_command "$1"

**Comment by Luligu** [comment]
Hi,
I'm glad you solved.
Thanks for your appreciation. 
My best.
