### ISSUE TITLE
LG WebOS TV Matter Hub "Device not Supported"

### ISSUE THREAD

**Issue by KingTomaHawk** [Luligu/matterbridge#95]
Hello, 

I just have discovered your app and wanted to test it with my new WebOS G4 Series with Matter Hub build in. 
I have only exposed a Bulb and tried to connect it to the TV. 
Unfortunaly the LG Thinq app says "device not supported". 

Is there anything I can do against it? It seems like I'm the first person who tries matterbridge with an LG OLED TV.

Thanks

**Comment by Apollon77** [comment]
The reason is that, from my knowledge, LG do not support bridges at all till now. I assume this functionality will come somewhen. But till now I would assume only normal Matter devices are supported but no bridges

**Comment by KingTomaHawk** [comment]
It seems like bridges are supported. The URL for supported devices is: https://quicksetcloud.com/works-with-quickset/lg-tv-2024/

**Comment by Apollon77** [comment]
Sure, this could also be, can you send a debug log of a commissioning try? @KingTomaHawk

**Comment by KingTomaHawk** [comment]
Thanks for the help, I appreciate it! Here is the log, I hope that it includes the important parts:
[Matterbridge.txt](https://github.com/user-attachments/files/16515268/Matterbridge.txt)

**Comment by Apollon77** [comment]
Question: How the commissioning is done? Via an iOS app? That would be my guess .... ?!

Hm .. log is interesting.

The log shows first of all a successfully commissioning ... if iOS was used then this is the iOS system com isssioner faberic which is "normal". if not Ios then ok ... but successful too

After this there is a wildcard attribute read to read anything on the device and then it removes the fabric again, so yes still a chance that it is the "test device thing".

**Comment by KingTomaHawk** [comment]
Hi,

the pairing process is done with the LG Thinq App for Android. It doesn't use the "build in" Matter Pairing wizard from Android, where a pop-up window in Android get shown. 

I hope it helps :)

**Comment by KingTomaHawk** [comment]
Is there anything else I can do to support you?

**Comment by Apollon77** [comment]
Nothing else beside writing LG about your issues :-)

**Comment by KingTomaHawk** [comment]
Sure will do, but can you tell me in simple words, what exactly is happening and what you would expect to happen to get matterbridge working with webos?
Otherwise I don't know what I should tell them other then "matterbridge doesn't work with webos". 😄
