### ISSUE TITLE
Use the current URL to determine whether to open a secure websocket connection 

### ISSUE THREAD

**Issue by milothomas** [Luligu/matterbridge#96]
I see that an insecure websocket connection is opened from `WebSocketUse.js` regardless of whether the application is accessed over SSL or not. Instead this is decided by a value returned from the call to `/api/settings`. 

This causes a problem when accessing over a reverse proxy via SSL. Can we use the `window.location.protocol` to determine whether to use `ws://` or `wss://`?

![image](https://github.com/user-attachments/assets/97b8455c-cf2f-4cec-937c-a62a87e5b7f4)

**Comment by Luligu** [comment]
Hi,
what version are you using?

If you use https (-ssl option) why your connection is not secured?

And why you don't use normal http if in your setup https is not working?

**Comment by milothomas** [comment]
> If you use https (-ssl option) why your connection is not secured?

Hi, where can I set this? Perhaps I missed it, but I don't remember seeing this option at all. 

> And why you don't use normal http if in your setup https is not working?

I want to access it behind a reverse proxy over SSL.

**Comment by Luligu** [comment]
If you don't add any parameter to the command line the frontend is served by a http server that serves also a websocket.
If you add the option -ssl you need to add your certificates and optionally also the CA certificate. In this case both frontend and websocket are served by https. The secure connection must be working if you use the -ssl.
<img width="238" alt="image" src="https://github.com/user-attachments/assets/a50b3176-5bb3-47c8-a9ca-e9a1070ccf08">

**Comment by milothomas** [comment]
Ah thanks. I am running matterbridge as a docker container, how would I specify this option?

**Comment by Luligu** [comment]
services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the dev tag
    restart: always # Ensures the container always restarts automatically
    network_mode: host # Ensures the Matter mdns works
    volumes:
      - "${HOME}/Matterbridge:/root/Matterbridge" # Mounts the Matterbridge plugin directory
      - "${HOME}/.matterbridge:/root/.matterbridge" # Mounts the Matterbridge storage directory
      - "${HOME}/Root:/root" # Mounts the root directory
    environment:
      - TZ=Europe/Paris
    command: [ "matterbridge", "-childbridge", "-docker" ]

You can add command and put what you need. Don't forget -docker if you override the default!

How to use -ssl:
check here https://github.com/Luligu/matterbridge/blob/main/CHANGELOG.md#136---2024-06-28

and matterbridge -help
