### ISSUE TITLE
Hello, I found that Matterbridge cannot connect to Tuya/smartlife and Aqara, and an error will be prompted. I guess could it be the reason that there is no Matter certification? Are there any other solutions?

### ISSUE THREAD

**Issue by yuanxin32323** [Luligu/matterbridge#97]
Hello, I found that Matterbridge cannot connect to Tuya/smartlife and Aqara, and an error will be prompted. I guess could it be the reason that there is no Matter certification? Are there any other solutions?

**Comment by Apollon77** [comment]
see https://github.com/Luligu/matterbridge/discussions/12#discussioncomment-9842058

**Comment by Luligu** [comment]
See also https://github.com/Luligu/matterbridge/issues/103

**Comment by yuanxin32323** [comment]
![image](https://github.com/user-attachments/assets/5902aa42-d33e-4cb4-8635-087557f082e3)

**Comment by Apollon77** [comment]
Try to restart the tuya app ... only one commisioning process can be in progress at a time
